#!/bin/bash

sh ./PIPELINE_ALL_REVERB.sh C61
sh ./BOOTSTRAP_ALL_REVERB.sh C61 2
sh ./BOOTSTRAP_ALL_REVERB.sh C61 3
sh ./BOOTSTRAP_ALL_REVERB.sh C61 4
sh ./BOOTSTRAP_ALL_REVERB.sh C61 5
sh ./BOOTSTRAP_ALL_REVERB.sh C61 6
sh ./BOOTSTRAP_ALL_REVERB.sh C61 7
echo "Done with complete reasoning of C61"

sh ./PIPELINE_ALL_REVERB.sh C62
sh ./BOOTSTRAP_ALL_REVERB.sh C62 2
sh ./BOOTSTRAP_ALL_REVERB.sh C62 3
sh ./BOOTSTRAP_ALL_REVERB.sh C62 4
sh ./BOOTSTRAP_ALL_REVERB.sh C62 5
sh ./BOOTSTRAP_ALL_REVERB.sh C62 6
sh ./BOOTSTRAP_ALL_REVERB.sh C62 7
echo "Done with complete reasoning of C62"

sh ./PIPELINE_ALL_REVERB.sh C60
sh ./BOOTSTRAP_ALL_REVERB.sh C60 2
sh ./BOOTSTRAP_ALL_REVERB.sh C60 3
sh ./BOOTSTRAP_ALL_REVERB.sh C60 4
sh ./BOOTSTRAP_ALL_REVERB.sh C60 5
sh ./BOOTSTRAP_ALL_REVERB.sh C60 6
sh ./BOOTSTRAP_ALL_REVERB.sh C60 7
echo "Done with complete reasoning of C60"

sh ./PIPELINE_ALL_REVERB.sh C59
sh ./BOOTSTRAP_ALL_REVERB.sh C59 2
sh ./BOOTSTRAP_ALL_REVERB.sh C59 3
sh ./BOOTSTRAP_ALL_REVERB.sh C59 4
sh ./BOOTSTRAP_ALL_REVERB.sh C59 5
sh ./BOOTSTRAP_ALL_REVERB.sh C59 6
sh ./BOOTSTRAP_ALL_REVERB.sh C59 7
echo "Done with complete reasoning of C59"

sh ./PIPELINE_ALL_REVERB.sh C58
sh ./BOOTSTRAP_ALL_REVERB.sh C58 2
sh ./BOOTSTRAP_ALL_REVERB.sh C58 3
sh ./BOOTSTRAP_ALL_REVERB.sh C58 4
sh ./BOOTSTRAP_ALL_REVERB.sh C58 5
sh ./BOOTSTRAP_ALL_REVERB.sh C58 6
sh ./BOOTSTRAP_ALL_REVERB.sh C58 7
echo "Done with complete reasoning of C58"

sh ./PIPELINE_ALL_REVERB.sh C57
sh ./BOOTSTRAP_ALL_REVERB.sh C57 2
sh ./BOOTSTRAP_ALL_REVERB.sh C57 3
sh ./BOOTSTRAP_ALL_REVERB.sh C57 4
sh ./BOOTSTRAP_ALL_REVERB.sh C57 5
sh ./BOOTSTRAP_ALL_REVERB.sh C57 6
sh ./BOOTSTRAP_ALL_REVERB.sh C57 7
echo "Done with complete reasoning of C57"

sh ./PIPELINE_ALL_REVERB.sh C56
sh ./BOOTSTRAP_ALL_REVERB.sh C56 2
sh ./BOOTSTRAP_ALL_REVERB.sh C56 3
sh ./BOOTSTRAP_ALL_REVERB.sh C56 4
sh ./BOOTSTRAP_ALL_REVERB.sh C56 5
sh ./BOOTSTRAP_ALL_REVERB.sh C56 6
sh ./BOOTSTRAP_ALL_REVERB.sh C56 7
echo "Done with complete reasoning of C56"

sh ./PIPELINE_ALL_REVERB.sh C55
sh ./BOOTSTRAP_ALL_REVERB.sh C55 2
sh ./BOOTSTRAP_ALL_REVERB.sh C55 3
sh ./BOOTSTRAP_ALL_REVERB.sh C55 4
sh ./BOOTSTRAP_ALL_REVERB.sh C55 5
sh ./BOOTSTRAP_ALL_REVERB.sh C55 6
sh ./BOOTSTRAP_ALL_REVERB.sh C55 7
echo "Done with complete reasoning of C55"

sh ./PIPELINE_ALL_REVERB.sh C54
sh ./BOOTSTRAP_ALL_REVERB.sh C54 2
sh ./BOOTSTRAP_ALL_REVERB.sh C54 3
sh ./BOOTSTRAP_ALL_REVERB.sh C54 4
sh ./BOOTSTRAP_ALL_REVERB.sh C54 5
sh ./BOOTSTRAP_ALL_REVERB.sh C54 6
sh ./BOOTSTRAP_ALL_REVERB.sh C54 7
echo "Done with complete reasoning of C54"

sh ./PIPELINE_ALL_REVERB.sh C53
sh ./BOOTSTRAP_ALL_REVERB.sh C53 2
sh ./BOOTSTRAP_ALL_REVERB.sh C53 3
sh ./BOOTSTRAP_ALL_REVERB.sh C53 4
sh ./BOOTSTRAP_ALL_REVERB.sh C53 5
sh ./BOOTSTRAP_ALL_REVERB.sh C53 6
sh ./BOOTSTRAP_ALL_REVERB.sh C53 7
echo "Done with complete reasoning of C53"

sh ./PIPELINE_ALL_REVERB.sh C52
sh ./BOOTSTRAP_ALL_REVERB.sh C52 2
sh ./BOOTSTRAP_ALL_REVERB.sh C52 3
sh ./BOOTSTRAP_ALL_REVERB.sh C52 4
sh ./BOOTSTRAP_ALL_REVERB.sh C52 5
sh ./BOOTSTRAP_ALL_REVERB.sh C52 6
sh ./BOOTSTRAP_ALL_REVERB.sh C52 7
echo "Done with complete reasoning of C52"

sh ./PIPELINE_ALL_REVERB.sh C16
sh ./BOOTSTRAP_ALL_REVERB.sh C16 2
sh ./BOOTSTRAP_ALL_REVERB.sh C16 3
sh ./BOOTSTRAP_ALL_REVERB.sh C16 4
sh ./BOOTSTRAP_ALL_REVERB.sh C16 5
sh ./BOOTSTRAP_ALL_REVERB.sh C16 6
sh ./BOOTSTRAP_ALL_REVERB.sh C16 7
echo "Done with complete reasoning of C16"

sh ./PIPELINE_ALL_REVERB.sh C17
sh ./BOOTSTRAP_ALL_REVERB.sh C17 2
sh ./BOOTSTRAP_ALL_REVERB.sh C17 3
sh ./BOOTSTRAP_ALL_REVERB.sh C17 4
sh ./BOOTSTRAP_ALL_REVERB.sh C17 5
sh ./BOOTSTRAP_ALL_REVERB.sh C17 6
sh ./BOOTSTRAP_ALL_REVERB.sh C17 7
echo "Done with complete reasoning of C17"

sh ./PIPELINE_ALL_REVERB.sh C18
sh ./BOOTSTRAP_ALL_REVERB.sh C18 2
sh ./BOOTSTRAP_ALL_REVERB.sh C18 3
sh ./BOOTSTRAP_ALL_REVERB.sh C18 4
sh ./BOOTSTRAP_ALL_REVERB.sh C18 5
sh ./BOOTSTRAP_ALL_REVERB.sh C18 6
sh ./BOOTSTRAP_ALL_REVERB.sh C18 7
echo "Done with complete reasoning of C18"

sh ./PIPELINE_ALL_REVERB.sh C19
sh ./BOOTSTRAP_ALL_REVERB.sh C19 2
sh ./BOOTSTRAP_ALL_REVERB.sh C19 3
sh ./BOOTSTRAP_ALL_REVERB.sh C19 4
sh ./BOOTSTRAP_ALL_REVERB.sh C19 5
sh ./BOOTSTRAP_ALL_REVERB.sh C19 6
sh ./BOOTSTRAP_ALL_REVERB.sh C19 7
echo "Done with complete reasoning of C19"

sh ./PIPELINE_ALL_REVERB.sh C50
sh ./BOOTSTRAP_ALL_REVERB.sh C50 2
sh ./BOOTSTRAP_ALL_REVERB.sh C50 3
sh ./BOOTSTRAP_ALL_REVERB.sh C50 4
sh ./BOOTSTRAP_ALL_REVERB.sh C50 5
sh ./BOOTSTRAP_ALL_REVERB.sh C50 6
sh ./BOOTSTRAP_ALL_REVERB.sh C50 7
echo "Done with complete reasoning of C50"

sh ./PIPELINE_ALL_REVERB.sh C10
sh ./BOOTSTRAP_ALL_REVERB.sh C10 2
sh ./BOOTSTRAP_ALL_REVERB.sh C10 3
sh ./BOOTSTRAP_ALL_REVERB.sh C10 4
sh ./BOOTSTRAP_ALL_REVERB.sh C10 5
sh ./BOOTSTRAP_ALL_REVERB.sh C10 6
sh ./BOOTSTRAP_ALL_REVERB.sh C10 7
echo "Done with complete reasoning of C10"

sh ./PIPELINE_ALL_REVERB.sh C51
sh ./BOOTSTRAP_ALL_REVERB.sh C51 2
sh ./BOOTSTRAP_ALL_REVERB.sh C51 3
sh ./BOOTSTRAP_ALL_REVERB.sh C51 4
sh ./BOOTSTRAP_ALL_REVERB.sh C51 5
sh ./BOOTSTRAP_ALL_REVERB.sh C51 6
sh ./BOOTSTRAP_ALL_REVERB.sh C51 7
echo "Done with complete reasoning of C51"

sh ./PIPELINE_ALL_REVERB.sh C11
sh ./BOOTSTRAP_ALL_REVERB.sh C11 2
sh ./BOOTSTRAP_ALL_REVERB.sh C11 3
sh ./BOOTSTRAP_ALL_REVERB.sh C11 4
sh ./BOOTSTRAP_ALL_REVERB.sh C11 5
sh ./BOOTSTRAP_ALL_REVERB.sh C11 6
sh ./BOOTSTRAP_ALL_REVERB.sh C11 7
echo "Done with complete reasoning of C11"

sh ./PIPELINE_ALL_REVERB.sh C12
sh ./BOOTSTRAP_ALL_REVERB.sh C12 2
sh ./BOOTSTRAP_ALL_REVERB.sh C12 3
sh ./BOOTSTRAP_ALL_REVERB.sh C12 4
sh ./BOOTSTRAP_ALL_REVERB.sh C12 5
sh ./BOOTSTRAP_ALL_REVERB.sh C12 6
sh ./BOOTSTRAP_ALL_REVERB.sh C12 7
echo "Done with complete reasoning of C12"

sh ./PIPELINE_ALL_REVERB.sh C13
sh ./BOOTSTRAP_ALL_REVERB.sh C13 2
sh ./BOOTSTRAP_ALL_REVERB.sh C13 3
sh ./BOOTSTRAP_ALL_REVERB.sh C13 4
sh ./BOOTSTRAP_ALL_REVERB.sh C13 5
sh ./BOOTSTRAP_ALL_REVERB.sh C13 6
sh ./BOOTSTRAP_ALL_REVERB.sh C13 7
echo "Done with complete reasoning of C13"

sh ./PIPELINE_ALL_REVERB.sh C14
sh ./BOOTSTRAP_ALL_REVERB.sh C14 2
sh ./BOOTSTRAP_ALL_REVERB.sh C14 3
sh ./BOOTSTRAP_ALL_REVERB.sh C14 4
sh ./BOOTSTRAP_ALL_REVERB.sh C14 5
sh ./BOOTSTRAP_ALL_REVERB.sh C14 6
sh ./BOOTSTRAP_ALL_REVERB.sh C14 7
echo "Done with complete reasoning of C14"

sh ./PIPELINE_ALL_REVERB.sh C15
sh ./BOOTSTRAP_ALL_REVERB.sh C15 2
sh ./BOOTSTRAP_ALL_REVERB.sh C15 3
sh ./BOOTSTRAP_ALL_REVERB.sh C15 4
sh ./BOOTSTRAP_ALL_REVERB.sh C15 5
sh ./BOOTSTRAP_ALL_REVERB.sh C15 6
sh ./BOOTSTRAP_ALL_REVERB.sh C15 7
echo "Done with complete reasoning of C15"

sh ./PIPELINE_ALL_REVERB.sh C46
sh ./BOOTSTRAP_ALL_REVERB.sh C46 2
sh ./BOOTSTRAP_ALL_REVERB.sh C46 3
sh ./BOOTSTRAP_ALL_REVERB.sh C46 4
sh ./BOOTSTRAP_ALL_REVERB.sh C46 5
sh ./BOOTSTRAP_ALL_REVERB.sh C46 6
sh ./BOOTSTRAP_ALL_REVERB.sh C46 7
echo "Done with complete reasoning of C46"

sh ./PIPELINE_ALL_REVERB.sh C45
sh ./BOOTSTRAP_ALL_REVERB.sh C45 2
sh ./BOOTSTRAP_ALL_REVERB.sh C45 3
sh ./BOOTSTRAP_ALL_REVERB.sh C45 4
sh ./BOOTSTRAP_ALL_REVERB.sh C45 5
sh ./BOOTSTRAP_ALL_REVERB.sh C45 6
sh ./BOOTSTRAP_ALL_REVERB.sh C45 7
echo "Done with complete reasoning of C45"

sh ./PIPELINE_ALL_REVERB.sh C48
sh ./BOOTSTRAP_ALL_REVERB.sh C48 2
sh ./BOOTSTRAP_ALL_REVERB.sh C48 3
sh ./BOOTSTRAP_ALL_REVERB.sh C48 4
sh ./BOOTSTRAP_ALL_REVERB.sh C48 5
sh ./BOOTSTRAP_ALL_REVERB.sh C48 6
sh ./BOOTSTRAP_ALL_REVERB.sh C48 7
echo "Done with complete reasoning of C48"

sh ./PIPELINE_ALL_REVERB.sh C47
sh ./BOOTSTRAP_ALL_REVERB.sh C47 2
sh ./BOOTSTRAP_ALL_REVERB.sh C47 3
sh ./BOOTSTRAP_ALL_REVERB.sh C47 4
sh ./BOOTSTRAP_ALL_REVERB.sh C47 5
sh ./BOOTSTRAP_ALL_REVERB.sh C47 6
sh ./BOOTSTRAP_ALL_REVERB.sh C47 7
echo "Done with complete reasoning of C47"

sh ./PIPELINE_ALL_REVERB.sh C42
sh ./BOOTSTRAP_ALL_REVERB.sh C42 2
sh ./BOOTSTRAP_ALL_REVERB.sh C42 3
sh ./BOOTSTRAP_ALL_REVERB.sh C42 4
sh ./BOOTSTRAP_ALL_REVERB.sh C42 5
sh ./BOOTSTRAP_ALL_REVERB.sh C42 6
sh ./BOOTSTRAP_ALL_REVERB.sh C42 7
echo "Done with complete reasoning of C42"

sh ./PIPELINE_ALL_REVERB.sh C41
sh ./BOOTSTRAP_ALL_REVERB.sh C41 2
sh ./BOOTSTRAP_ALL_REVERB.sh C41 3
sh ./BOOTSTRAP_ALL_REVERB.sh C41 4
sh ./BOOTSTRAP_ALL_REVERB.sh C41 5
sh ./BOOTSTRAP_ALL_REVERB.sh C41 6
sh ./BOOTSTRAP_ALL_REVERB.sh C41 7
echo "Done with complete reasoning of C41"

sh ./PIPELINE_ALL_REVERB.sh C44
sh ./BOOTSTRAP_ALL_REVERB.sh C44 2
sh ./BOOTSTRAP_ALL_REVERB.sh C44 3
sh ./BOOTSTRAP_ALL_REVERB.sh C44 4
sh ./BOOTSTRAP_ALL_REVERB.sh C44 5
sh ./BOOTSTRAP_ALL_REVERB.sh C44 6
sh ./BOOTSTRAP_ALL_REVERB.sh C44 7
echo "Done with complete reasoning of C44"

sh ./PIPELINE_ALL_REVERB.sh C43
sh ./BOOTSTRAP_ALL_REVERB.sh C43 2
sh ./BOOTSTRAP_ALL_REVERB.sh C43 3
sh ./BOOTSTRAP_ALL_REVERB.sh C43 4
sh ./BOOTSTRAP_ALL_REVERB.sh C43 5
sh ./BOOTSTRAP_ALL_REVERB.sh C43 6
sh ./BOOTSTRAP_ALL_REVERB.sh C43 7
echo "Done with complete reasoning of C43"

sh ./PIPELINE_ALL_REVERB.sh C49
sh ./BOOTSTRAP_ALL_REVERB.sh C49 2
sh ./BOOTSTRAP_ALL_REVERB.sh C49 3
sh ./BOOTSTRAP_ALL_REVERB.sh C49 4
sh ./BOOTSTRAP_ALL_REVERB.sh C49 5
sh ./BOOTSTRAP_ALL_REVERB.sh C49 6
sh ./BOOTSTRAP_ALL_REVERB.sh C49 7
echo "Done with complete reasoning of C49"

sh ./PIPELINE_ALL_REVERB.sh C8
sh ./BOOTSTRAP_ALL_REVERB.sh C8 2
sh ./BOOTSTRAP_ALL_REVERB.sh C8 3
sh ./BOOTSTRAP_ALL_REVERB.sh C8 4
sh ./BOOTSTRAP_ALL_REVERB.sh C8 5
sh ./BOOTSTRAP_ALL_REVERB.sh C8 6
sh ./BOOTSTRAP_ALL_REVERB.sh C8 7
echo "Done with complete reasoning of C8"

sh ./PIPELINE_ALL_REVERB.sh C7
sh ./BOOTSTRAP_ALL_REVERB.sh C7 2
sh ./BOOTSTRAP_ALL_REVERB.sh C7 3
sh ./BOOTSTRAP_ALL_REVERB.sh C7 4
sh ./BOOTSTRAP_ALL_REVERB.sh C7 5
sh ./BOOTSTRAP_ALL_REVERB.sh C7 6
sh ./BOOTSTRAP_ALL_REVERB.sh C7 7
echo "Done with complete reasoning of C7"

sh ./PIPELINE_ALL_REVERB.sh C9
sh ./BOOTSTRAP_ALL_REVERB.sh C9 2
sh ./BOOTSTRAP_ALL_REVERB.sh C9 3
sh ./BOOTSTRAP_ALL_REVERB.sh C9 4
sh ./BOOTSTRAP_ALL_REVERB.sh C9 5
sh ./BOOTSTRAP_ALL_REVERB.sh C9 6
sh ./BOOTSTRAP_ALL_REVERB.sh C9 7
echo "Done with complete reasoning of C9"

sh ./PIPELINE_ALL_REVERB.sh C4
sh ./BOOTSTRAP_ALL_REVERB.sh C4 2
sh ./BOOTSTRAP_ALL_REVERB.sh C4 3
sh ./BOOTSTRAP_ALL_REVERB.sh C4 4
sh ./BOOTSTRAP_ALL_REVERB.sh C4 5
sh ./BOOTSTRAP_ALL_REVERB.sh C4 6
sh ./BOOTSTRAP_ALL_REVERB.sh C4 7
echo "Done with complete reasoning of C4"

sh ./PIPELINE_ALL_REVERB.sh C29
sh ./BOOTSTRAP_ALL_REVERB.sh C29 2
sh ./BOOTSTRAP_ALL_REVERB.sh C29 3
sh ./BOOTSTRAP_ALL_REVERB.sh C29 4
sh ./BOOTSTRAP_ALL_REVERB.sh C29 5
sh ./BOOTSTRAP_ALL_REVERB.sh C29 6
sh ./BOOTSTRAP_ALL_REVERB.sh C29 7
echo "Done with complete reasoning of C29"

sh ./PIPELINE_ALL_REVERB.sh C3
sh ./BOOTSTRAP_ALL_REVERB.sh C3 2
sh ./BOOTSTRAP_ALL_REVERB.sh C3 3
sh ./BOOTSTRAP_ALL_REVERB.sh C3 4
sh ./BOOTSTRAP_ALL_REVERB.sh C3 5
sh ./BOOTSTRAP_ALL_REVERB.sh C3 6
sh ./BOOTSTRAP_ALL_REVERB.sh C3 7
echo "Done with complete reasoning of C3"

sh ./PIPELINE_ALL_REVERB.sh C6
sh ./BOOTSTRAP_ALL_REVERB.sh C6 2
sh ./BOOTSTRAP_ALL_REVERB.sh C6 3
sh ./BOOTSTRAP_ALL_REVERB.sh C6 4
sh ./BOOTSTRAP_ALL_REVERB.sh C6 5
sh ./BOOTSTRAP_ALL_REVERB.sh C6 6
sh ./BOOTSTRAP_ALL_REVERB.sh C6 7
echo "Done with complete reasoning of C6"

sh ./PIPELINE_ALL_REVERB.sh C27
sh ./BOOTSTRAP_ALL_REVERB.sh C27 2
sh ./BOOTSTRAP_ALL_REVERB.sh C27 3
sh ./BOOTSTRAP_ALL_REVERB.sh C27 4
sh ./BOOTSTRAP_ALL_REVERB.sh C27 5
sh ./BOOTSTRAP_ALL_REVERB.sh C27 6
sh ./BOOTSTRAP_ALL_REVERB.sh C27 7
echo "Done with complete reasoning of C27"

sh ./PIPELINE_ALL_REVERB.sh C5
sh ./BOOTSTRAP_ALL_REVERB.sh C5 2
sh ./BOOTSTRAP_ALL_REVERB.sh C5 3
sh ./BOOTSTRAP_ALL_REVERB.sh C5 4
sh ./BOOTSTRAP_ALL_REVERB.sh C5 5
sh ./BOOTSTRAP_ALL_REVERB.sh C5 6
sh ./BOOTSTRAP_ALL_REVERB.sh C5 7
echo "Done with complete reasoning of C5"

sh ./PIPELINE_ALL_REVERB.sh C28
sh ./BOOTSTRAP_ALL_REVERB.sh C28 2
sh ./BOOTSTRAP_ALL_REVERB.sh C28 3
sh ./BOOTSTRAP_ALL_REVERB.sh C28 4
sh ./BOOTSTRAP_ALL_REVERB.sh C28 5
sh ./BOOTSTRAP_ALL_REVERB.sh C28 6
sh ./BOOTSTRAP_ALL_REVERB.sh C28 7
echo "Done with complete reasoning of C28"

sh ./PIPELINE_ALL_REVERB.sh C25
sh ./BOOTSTRAP_ALL_REVERB.sh C25 2
sh ./BOOTSTRAP_ALL_REVERB.sh C25 3
sh ./BOOTSTRAP_ALL_REVERB.sh C25 4
sh ./BOOTSTRAP_ALL_REVERB.sh C25 5
sh ./BOOTSTRAP_ALL_REVERB.sh C25 6
sh ./BOOTSTRAP_ALL_REVERB.sh C25 7
echo "Done with complete reasoning of C25"

sh ./PIPELINE_ALL_REVERB.sh C80
sh ./BOOTSTRAP_ALL_REVERB.sh C80 2
sh ./BOOTSTRAP_ALL_REVERB.sh C80 3
sh ./BOOTSTRAP_ALL_REVERB.sh C80 4
sh ./BOOTSTRAP_ALL_REVERB.sh C80 5
sh ./BOOTSTRAP_ALL_REVERB.sh C80 6
sh ./BOOTSTRAP_ALL_REVERB.sh C80 7
echo "Done with complete reasoning of C80"

sh ./PIPELINE_ALL_REVERB.sh C26
sh ./BOOTSTRAP_ALL_REVERB.sh C26 2
sh ./BOOTSTRAP_ALL_REVERB.sh C26 3
sh ./BOOTSTRAP_ALL_REVERB.sh C26 4
sh ./BOOTSTRAP_ALL_REVERB.sh C26 5
sh ./BOOTSTRAP_ALL_REVERB.sh C26 6
sh ./BOOTSTRAP_ALL_REVERB.sh C26 7
echo "Done with complete reasoning of C26"

sh ./PIPELINE_ALL_REVERB.sh C23
sh ./BOOTSTRAP_ALL_REVERB.sh C23 2
sh ./BOOTSTRAP_ALL_REVERB.sh C23 3
sh ./BOOTSTRAP_ALL_REVERB.sh C23 4
sh ./BOOTSTRAP_ALL_REVERB.sh C23 5
sh ./BOOTSTRAP_ALL_REVERB.sh C23 6
sh ./BOOTSTRAP_ALL_REVERB.sh C23 7
echo "Done with complete reasoning of C23"

sh ./PIPELINE_ALL_REVERB.sh C24
sh ./BOOTSTRAP_ALL_REVERB.sh C24 2
sh ./BOOTSTRAP_ALL_REVERB.sh C24 3
sh ./BOOTSTRAP_ALL_REVERB.sh C24 4
sh ./BOOTSTRAP_ALL_REVERB.sh C24 5
sh ./BOOTSTRAP_ALL_REVERB.sh C24 6
sh ./BOOTSTRAP_ALL_REVERB.sh C24 7
echo "Done with complete reasoning of C24"

sh ./PIPELINE_ALL_REVERB.sh C83
sh ./BOOTSTRAP_ALL_REVERB.sh C83 2
sh ./BOOTSTRAP_ALL_REVERB.sh C83 3
sh ./BOOTSTRAP_ALL_REVERB.sh C83 4
sh ./BOOTSTRAP_ALL_REVERB.sh C83 5
sh ./BOOTSTRAP_ALL_REVERB.sh C83 6
sh ./BOOTSTRAP_ALL_REVERB.sh C83 7
echo "Done with complete reasoning of C83"

sh ./PIPELINE_ALL_REVERB.sh C21
sh ./BOOTSTRAP_ALL_REVERB.sh C21 2
sh ./BOOTSTRAP_ALL_REVERB.sh C21 3
sh ./BOOTSTRAP_ALL_REVERB.sh C21 4
sh ./BOOTSTRAP_ALL_REVERB.sh C21 5
sh ./BOOTSTRAP_ALL_REVERB.sh C21 6
sh ./BOOTSTRAP_ALL_REVERB.sh C21 7
echo "Done with complete reasoning of C21"

sh ./PIPELINE_ALL_REVERB.sh C22
sh ./BOOTSTRAP_ALL_REVERB.sh C22 2
sh ./BOOTSTRAP_ALL_REVERB.sh C22 3
sh ./BOOTSTRAP_ALL_REVERB.sh C22 4
sh ./BOOTSTRAP_ALL_REVERB.sh C22 5
sh ./BOOTSTRAP_ALL_REVERB.sh C22 6
sh ./BOOTSTRAP_ALL_REVERB.sh C22 7
echo "Done with complete reasoning of C22"

sh ./PIPELINE_ALL_REVERB.sh C81
sh ./BOOTSTRAP_ALL_REVERB.sh C81 2
sh ./BOOTSTRAP_ALL_REVERB.sh C81 3
sh ./BOOTSTRAP_ALL_REVERB.sh C81 4
sh ./BOOTSTRAP_ALL_REVERB.sh C81 5
sh ./BOOTSTRAP_ALL_REVERB.sh C81 6
sh ./BOOTSTRAP_ALL_REVERB.sh C81 7
echo "Done with complete reasoning of C81"

sh ./PIPELINE_ALL_REVERB.sh C82
sh ./BOOTSTRAP_ALL_REVERB.sh C82 2
sh ./BOOTSTRAP_ALL_REVERB.sh C82 3
sh ./BOOTSTRAP_ALL_REVERB.sh C82 4
sh ./BOOTSTRAP_ALL_REVERB.sh C82 5
sh ./BOOTSTRAP_ALL_REVERB.sh C82 6
sh ./BOOTSTRAP_ALL_REVERB.sh C82 7
echo "Done with complete reasoning of C82"

sh ./PIPELINE_ALL_REVERB.sh C20
sh ./BOOTSTRAP_ALL_REVERB.sh C20 2
sh ./BOOTSTRAP_ALL_REVERB.sh C20 3
sh ./BOOTSTRAP_ALL_REVERB.sh C20 4
sh ./BOOTSTRAP_ALL_REVERB.sh C20 5
sh ./BOOTSTRAP_ALL_REVERB.sh C20 6
sh ./BOOTSTRAP_ALL_REVERB.sh C20 7
echo "Done with complete reasoning of C20"

sh ./PIPELINE_ALL_REVERB.sh C77
sh ./BOOTSTRAP_ALL_REVERB.sh C77 2
sh ./BOOTSTRAP_ALL_REVERB.sh C77 3
sh ./BOOTSTRAP_ALL_REVERB.sh C77 4
sh ./BOOTSTRAP_ALL_REVERB.sh C77 5
sh ./BOOTSTRAP_ALL_REVERB.sh C77 6
sh ./BOOTSTRAP_ALL_REVERB.sh C77 7
echo "Done with complete reasoning of C77"

sh ./PIPELINE_ALL_REVERB.sh C76
sh ./BOOTSTRAP_ALL_REVERB.sh C76 2
sh ./BOOTSTRAP_ALL_REVERB.sh C76 3
sh ./BOOTSTRAP_ALL_REVERB.sh C76 4
sh ./BOOTSTRAP_ALL_REVERB.sh C76 5
sh ./BOOTSTRAP_ALL_REVERB.sh C76 6
sh ./BOOTSTRAP_ALL_REVERB.sh C76 7
echo "Done with complete reasoning of C76"

sh ./PIPELINE_ALL_REVERB.sh C75
sh ./BOOTSTRAP_ALL_REVERB.sh C75 2
sh ./BOOTSTRAP_ALL_REVERB.sh C75 3
sh ./BOOTSTRAP_ALL_REVERB.sh C75 4
sh ./BOOTSTRAP_ALL_REVERB.sh C75 5
sh ./BOOTSTRAP_ALL_REVERB.sh C75 6
sh ./BOOTSTRAP_ALL_REVERB.sh C75 7
echo "Done with complete reasoning of C75"

sh ./PIPELINE_ALL_REVERB.sh C74
sh ./BOOTSTRAP_ALL_REVERB.sh C74 2
sh ./BOOTSTRAP_ALL_REVERB.sh C74 3
sh ./BOOTSTRAP_ALL_REVERB.sh C74 4
sh ./BOOTSTRAP_ALL_REVERB.sh C74 5
sh ./BOOTSTRAP_ALL_REVERB.sh C74 6
sh ./BOOTSTRAP_ALL_REVERB.sh C74 7
echo "Done with complete reasoning of C74"

sh ./PIPELINE_ALL_REVERB.sh C79
sh ./BOOTSTRAP_ALL_REVERB.sh C79 2
sh ./BOOTSTRAP_ALL_REVERB.sh C79 3
sh ./BOOTSTRAP_ALL_REVERB.sh C79 4
sh ./BOOTSTRAP_ALL_REVERB.sh C79 5
sh ./BOOTSTRAP_ALL_REVERB.sh C79 6
sh ./BOOTSTRAP_ALL_REVERB.sh C79 7
echo "Done with complete reasoning of C79"

sh ./PIPELINE_ALL_REVERB.sh C78
sh ./BOOTSTRAP_ALL_REVERB.sh C78 2
sh ./BOOTSTRAP_ALL_REVERB.sh C78 3
sh ./BOOTSTRAP_ALL_REVERB.sh C78 4
sh ./BOOTSTRAP_ALL_REVERB.sh C78 5
sh ./BOOTSTRAP_ALL_REVERB.sh C78 6
sh ./BOOTSTRAP_ALL_REVERB.sh C78 7
echo "Done with complete reasoning of C78"

sh ./PIPELINE_ALL_REVERB.sh C1
sh ./BOOTSTRAP_ALL_REVERB.sh C1 2
sh ./BOOTSTRAP_ALL_REVERB.sh C1 3
sh ./BOOTSTRAP_ALL_REVERB.sh C1 4
sh ./BOOTSTRAP_ALL_REVERB.sh C1 5
sh ./BOOTSTRAP_ALL_REVERB.sh C1 6
sh ./BOOTSTRAP_ALL_REVERB.sh C1 7
echo "Done with complete reasoning of C1"

sh ./PIPELINE_ALL_REVERB.sh C2
sh ./BOOTSTRAP_ALL_REVERB.sh C2 2
sh ./BOOTSTRAP_ALL_REVERB.sh C2 3
sh ./BOOTSTRAP_ALL_REVERB.sh C2 4
sh ./BOOTSTRAP_ALL_REVERB.sh C2 5
sh ./BOOTSTRAP_ALL_REVERB.sh C2 6
sh ./BOOTSTRAP_ALL_REVERB.sh C2 7
echo "Done with complete reasoning of C2"

sh ./PIPELINE_ALL_REVERB.sh C38
sh ./BOOTSTRAP_ALL_REVERB.sh C38 2
sh ./BOOTSTRAP_ALL_REVERB.sh C38 3
sh ./BOOTSTRAP_ALL_REVERB.sh C38 4
sh ./BOOTSTRAP_ALL_REVERB.sh C38 5
sh ./BOOTSTRAP_ALL_REVERB.sh C38 6
sh ./BOOTSTRAP_ALL_REVERB.sh C38 7
echo "Done with complete reasoning of C38"

sh ./PIPELINE_ALL_REVERB.sh C39
sh ./BOOTSTRAP_ALL_REVERB.sh C39 2
sh ./BOOTSTRAP_ALL_REVERB.sh C39 3
sh ./BOOTSTRAP_ALL_REVERB.sh C39 4
sh ./BOOTSTRAP_ALL_REVERB.sh C39 5
sh ./BOOTSTRAP_ALL_REVERB.sh C39 6
sh ./BOOTSTRAP_ALL_REVERB.sh C39 7
echo "Done with complete reasoning of C39"

sh ./PIPELINE_ALL_REVERB.sh C34
sh ./BOOTSTRAP_ALL_REVERB.sh C34 2
sh ./BOOTSTRAP_ALL_REVERB.sh C34 3
sh ./BOOTSTRAP_ALL_REVERB.sh C34 4
sh ./BOOTSTRAP_ALL_REVERB.sh C34 5
sh ./BOOTSTRAP_ALL_REVERB.sh C34 6
sh ./BOOTSTRAP_ALL_REVERB.sh C34 7
echo "Done with complete reasoning of C34"

sh ./PIPELINE_ALL_REVERB.sh C35
sh ./BOOTSTRAP_ALL_REVERB.sh C35 2
sh ./BOOTSTRAP_ALL_REVERB.sh C35 3
sh ./BOOTSTRAP_ALL_REVERB.sh C35 4
sh ./BOOTSTRAP_ALL_REVERB.sh C35 5
sh ./BOOTSTRAP_ALL_REVERB.sh C35 6
sh ./BOOTSTRAP_ALL_REVERB.sh C35 7
echo "Done with complete reasoning of C35"

sh ./PIPELINE_ALL_REVERB.sh C36
sh ./BOOTSTRAP_ALL_REVERB.sh C36 2
sh ./BOOTSTRAP_ALL_REVERB.sh C36 3
sh ./BOOTSTRAP_ALL_REVERB.sh C36 4
sh ./BOOTSTRAP_ALL_REVERB.sh C36 5
sh ./BOOTSTRAP_ALL_REVERB.sh C36 6
sh ./BOOTSTRAP_ALL_REVERB.sh C36 7
echo "Done with complete reasoning of C36"

sh ./PIPELINE_ALL_REVERB.sh C37
sh ./BOOTSTRAP_ALL_REVERB.sh C37 2
sh ./BOOTSTRAP_ALL_REVERB.sh C37 3
sh ./BOOTSTRAP_ALL_REVERB.sh C37 4
sh ./BOOTSTRAP_ALL_REVERB.sh C37 5
sh ./BOOTSTRAP_ALL_REVERB.sh C37 6
sh ./BOOTSTRAP_ALL_REVERB.sh C37 7
echo "Done with complete reasoning of C37"

sh ./PIPELINE_ALL_REVERB.sh C70
sh ./BOOTSTRAP_ALL_REVERB.sh C70 2
sh ./BOOTSTRAP_ALL_REVERB.sh C70 3
sh ./BOOTSTRAP_ALL_REVERB.sh C70 4
sh ./BOOTSTRAP_ALL_REVERB.sh C70 5
sh ./BOOTSTRAP_ALL_REVERB.sh C70 6
sh ./BOOTSTRAP_ALL_REVERB.sh C70 7
echo "Done with complete reasoning of C70"

sh ./PIPELINE_ALL_REVERB.sh C30
sh ./BOOTSTRAP_ALL_REVERB.sh C30 2
sh ./BOOTSTRAP_ALL_REVERB.sh C30 3
sh ./BOOTSTRAP_ALL_REVERB.sh C30 4
sh ./BOOTSTRAP_ALL_REVERB.sh C30 5
sh ./BOOTSTRAP_ALL_REVERB.sh C30 6
sh ./BOOTSTRAP_ALL_REVERB.sh C30 7
echo "Done with complete reasoning of C30"

sh ./PIPELINE_ALL_REVERB.sh C71
sh ./BOOTSTRAP_ALL_REVERB.sh C71 2
sh ./BOOTSTRAP_ALL_REVERB.sh C71 3
sh ./BOOTSTRAP_ALL_REVERB.sh C71 4
sh ./BOOTSTRAP_ALL_REVERB.sh C71 5
sh ./BOOTSTRAP_ALL_REVERB.sh C71 6
sh ./BOOTSTRAP_ALL_REVERB.sh C71 7
echo "Done with complete reasoning of C71"

sh ./PIPELINE_ALL_REVERB.sh C31
sh ./BOOTSTRAP_ALL_REVERB.sh C31 2
sh ./BOOTSTRAP_ALL_REVERB.sh C31 3
sh ./BOOTSTRAP_ALL_REVERB.sh C31 4
sh ./BOOTSTRAP_ALL_REVERB.sh C31 5
sh ./BOOTSTRAP_ALL_REVERB.sh C31 6
sh ./BOOTSTRAP_ALL_REVERB.sh C31 7
echo "Done with complete reasoning of C31"

sh ./PIPELINE_ALL_REVERB.sh C72
sh ./BOOTSTRAP_ALL_REVERB.sh C72 2
sh ./BOOTSTRAP_ALL_REVERB.sh C72 3
sh ./BOOTSTRAP_ALL_REVERB.sh C72 4
sh ./BOOTSTRAP_ALL_REVERB.sh C72 5
sh ./BOOTSTRAP_ALL_REVERB.sh C72 6
sh ./BOOTSTRAP_ALL_REVERB.sh C72 7
echo "Done with complete reasoning of C72"

sh ./PIPELINE_ALL_REVERB.sh C32
sh ./BOOTSTRAP_ALL_REVERB.sh C32 2
sh ./BOOTSTRAP_ALL_REVERB.sh C32 3
sh ./BOOTSTRAP_ALL_REVERB.sh C32 4
sh ./BOOTSTRAP_ALL_REVERB.sh C32 5
sh ./BOOTSTRAP_ALL_REVERB.sh C32 6
sh ./BOOTSTRAP_ALL_REVERB.sh C32 7
echo "Done with complete reasoning of C32"

sh ./PIPELINE_ALL_REVERB.sh C73
sh ./BOOTSTRAP_ALL_REVERB.sh C73 2
sh ./BOOTSTRAP_ALL_REVERB.sh C73 3
sh ./BOOTSTRAP_ALL_REVERB.sh C73 4
sh ./BOOTSTRAP_ALL_REVERB.sh C73 5
sh ./BOOTSTRAP_ALL_REVERB.sh C73 6
sh ./BOOTSTRAP_ALL_REVERB.sh C73 7
echo "Done with complete reasoning of C73"

sh ./PIPELINE_ALL_REVERB.sh C33
sh ./BOOTSTRAP_ALL_REVERB.sh C33 2
sh ./BOOTSTRAP_ALL_REVERB.sh C33 3
sh ./BOOTSTRAP_ALL_REVERB.sh C33 4
sh ./BOOTSTRAP_ALL_REVERB.sh C33 5
sh ./BOOTSTRAP_ALL_REVERB.sh C33 6
sh ./BOOTSTRAP_ALL_REVERB.sh C33 7
echo "Done with complete reasoning of C33"

sh ./PIPELINE_ALL_REVERB.sh C64
sh ./BOOTSTRAP_ALL_REVERB.sh C64 2
sh ./BOOTSTRAP_ALL_REVERB.sh C64 3
sh ./BOOTSTRAP_ALL_REVERB.sh C64 4
sh ./BOOTSTRAP_ALL_REVERB.sh C64 5
sh ./BOOTSTRAP_ALL_REVERB.sh C64 6
sh ./BOOTSTRAP_ALL_REVERB.sh C64 7
echo "Done with complete reasoning of C64"

sh ./PIPELINE_ALL_REVERB.sh C63
sh ./BOOTSTRAP_ALL_REVERB.sh C63 2
sh ./BOOTSTRAP_ALL_REVERB.sh C63 3
sh ./BOOTSTRAP_ALL_REVERB.sh C63 4
sh ./BOOTSTRAP_ALL_REVERB.sh C63 5
sh ./BOOTSTRAP_ALL_REVERB.sh C63 6
sh ./BOOTSTRAP_ALL_REVERB.sh C63 7
echo "Done with complete reasoning of C63"

sh ./PIPELINE_ALL_REVERB.sh C66
sh ./BOOTSTRAP_ALL_REVERB.sh C66 2
sh ./BOOTSTRAP_ALL_REVERB.sh C66 3
sh ./BOOTSTRAP_ALL_REVERB.sh C66 4
sh ./BOOTSTRAP_ALL_REVERB.sh C66 5
sh ./BOOTSTRAP_ALL_REVERB.sh C66 6
sh ./BOOTSTRAP_ALL_REVERB.sh C66 7
echo "Done with complete reasoning of C66"

sh ./PIPELINE_ALL_REVERB.sh C40
sh ./BOOTSTRAP_ALL_REVERB.sh C40 2
sh ./BOOTSTRAP_ALL_REVERB.sh C40 3
sh ./BOOTSTRAP_ALL_REVERB.sh C40 4
sh ./BOOTSTRAP_ALL_REVERB.sh C40 5
sh ./BOOTSTRAP_ALL_REVERB.sh C40 6
sh ./BOOTSTRAP_ALL_REVERB.sh C40 7
echo "Done with complete reasoning of C40"

sh ./PIPELINE_ALL_REVERB.sh C65
sh ./BOOTSTRAP_ALL_REVERB.sh C65 2
sh ./BOOTSTRAP_ALL_REVERB.sh C65 3
sh ./BOOTSTRAP_ALL_REVERB.sh C65 4
sh ./BOOTSTRAP_ALL_REVERB.sh C65 5
sh ./BOOTSTRAP_ALL_REVERB.sh C65 6
sh ./BOOTSTRAP_ALL_REVERB.sh C65 7
echo "Done with complete reasoning of C65"

sh ./PIPELINE_ALL_REVERB.sh C68
sh ./BOOTSTRAP_ALL_REVERB.sh C68 2
sh ./BOOTSTRAP_ALL_REVERB.sh C68 3
sh ./BOOTSTRAP_ALL_REVERB.sh C68 4
sh ./BOOTSTRAP_ALL_REVERB.sh C68 5
sh ./BOOTSTRAP_ALL_REVERB.sh C68 6
sh ./BOOTSTRAP_ALL_REVERB.sh C68 7
echo "Done with complete reasoning of C68"

sh ./PIPELINE_ALL_REVERB.sh C67
sh ./BOOTSTRAP_ALL_REVERB.sh C67 2
sh ./BOOTSTRAP_ALL_REVERB.sh C67 3
sh ./BOOTSTRAP_ALL_REVERB.sh C67 4
sh ./BOOTSTRAP_ALL_REVERB.sh C67 5
sh ./BOOTSTRAP_ALL_REVERB.sh C67 6
sh ./BOOTSTRAP_ALL_REVERB.sh C67 7
echo "Done with complete reasoning of C67"

sh ./PIPELINE_ALL_REVERB.sh C69
sh ./BOOTSTRAP_ALL_REVERB.sh C69 2
sh ./BOOTSTRAP_ALL_REVERB.sh C69 3
sh ./BOOTSTRAP_ALL_REVERB.sh C69 4
sh ./BOOTSTRAP_ALL_REVERB.sh C69 5
sh ./BOOTSTRAP_ALL_REVERB.sh C69 6
sh ./BOOTSTRAP_ALL_REVERB.sh C69 7
echo "Done with complete reasoning of C69"

