#!/bin/bash

sh ./PIPELINE_ALL_REVERB.sh C179
sh ./BOOTSTRAP_ALL_REVERB.sh C179 2
sh ./BOOTSTRAP_ALL_REVERB.sh C179 3
sh ./BOOTSTRAP_ALL_REVERB.sh C179 4
echo "Done with complete reasoning of C179"

sh ./PIPELINE_ALL_REVERB.sh C61
sh ./BOOTSTRAP_ALL_REVERB.sh C61 2
sh ./BOOTSTRAP_ALL_REVERB.sh C61 3
sh ./BOOTSTRAP_ALL_REVERB.sh C61 4
echo "Done with complete reasoning of C61"

sh ./PIPELINE_ALL_REVERB.sh C62
sh ./BOOTSTRAP_ALL_REVERB.sh C62 2
sh ./BOOTSTRAP_ALL_REVERB.sh C62 3
sh ./BOOTSTRAP_ALL_REVERB.sh C62 4
echo "Done with complete reasoning of C62"

sh ./PIPELINE_ALL_REVERB.sh C60
sh ./BOOTSTRAP_ALL_REVERB.sh C60 2
sh ./BOOTSTRAP_ALL_REVERB.sh C60 3
sh ./BOOTSTRAP_ALL_REVERB.sh C60 4
echo "Done with complete reasoning of C60"

sh ./PIPELINE_ALL_REVERB.sh C59
sh ./BOOTSTRAP_ALL_REVERB.sh C59 2
sh ./BOOTSTRAP_ALL_REVERB.sh C59 3
sh ./BOOTSTRAP_ALL_REVERB.sh C59 4
echo "Done with complete reasoning of C59"

sh ./PIPELINE_ALL_REVERB.sh C58
sh ./BOOTSTRAP_ALL_REVERB.sh C58 2
sh ./BOOTSTRAP_ALL_REVERB.sh C58 3
sh ./BOOTSTRAP_ALL_REVERB.sh C58 4
echo "Done with complete reasoning of C58"

sh ./PIPELINE_ALL_REVERB.sh C57
sh ./BOOTSTRAP_ALL_REVERB.sh C57 2
sh ./BOOTSTRAP_ALL_REVERB.sh C57 3
sh ./BOOTSTRAP_ALL_REVERB.sh C57 4
echo "Done with complete reasoning of C57"

sh ./PIPELINE_ALL_REVERB.sh C56
sh ./BOOTSTRAP_ALL_REVERB.sh C56 2
sh ./BOOTSTRAP_ALL_REVERB.sh C56 3
sh ./BOOTSTRAP_ALL_REVERB.sh C56 4
echo "Done with complete reasoning of C56"

sh ./PIPELINE_ALL_REVERB.sh C170
sh ./BOOTSTRAP_ALL_REVERB.sh C170 2
sh ./BOOTSTRAP_ALL_REVERB.sh C170 3
sh ./BOOTSTRAP_ALL_REVERB.sh C170 4
echo "Done with complete reasoning of C170"

sh ./PIPELINE_ALL_REVERB.sh C55
sh ./BOOTSTRAP_ALL_REVERB.sh C55 2
sh ./BOOTSTRAP_ALL_REVERB.sh C55 3
sh ./BOOTSTRAP_ALL_REVERB.sh C55 4
echo "Done with complete reasoning of C55"

sh ./PIPELINE_ALL_REVERB.sh C54
sh ./BOOTSTRAP_ALL_REVERB.sh C54 2
sh ./BOOTSTRAP_ALL_REVERB.sh C54 3
sh ./BOOTSTRAP_ALL_REVERB.sh C54 4
echo "Done with complete reasoning of C54"

sh ./PIPELINE_ALL_REVERB.sh C53
sh ./BOOTSTRAP_ALL_REVERB.sh C53 2
sh ./BOOTSTRAP_ALL_REVERB.sh C53 3
sh ./BOOTSTRAP_ALL_REVERB.sh C53 4
echo "Done with complete reasoning of C53"

sh ./PIPELINE_ALL_REVERB.sh C52
sh ./BOOTSTRAP_ALL_REVERB.sh C52 2
sh ./BOOTSTRAP_ALL_REVERB.sh C52 3
sh ./BOOTSTRAP_ALL_REVERB.sh C52 4
echo "Done with complete reasoning of C52"

sh ./PIPELINE_ALL_REVERB.sh C174
sh ./BOOTSTRAP_ALL_REVERB.sh C174 2
sh ./BOOTSTRAP_ALL_REVERB.sh C174 3
sh ./BOOTSTRAP_ALL_REVERB.sh C174 4
echo "Done with complete reasoning of C174"

sh ./PIPELINE_ALL_REVERB.sh C173
sh ./BOOTSTRAP_ALL_REVERB.sh C173 2
sh ./BOOTSTRAP_ALL_REVERB.sh C173 3
sh ./BOOTSTRAP_ALL_REVERB.sh C173 4
echo "Done with complete reasoning of C173"

sh ./PIPELINE_ALL_REVERB.sh C172
sh ./BOOTSTRAP_ALL_REVERB.sh C172 2
sh ./BOOTSTRAP_ALL_REVERB.sh C172 3
sh ./BOOTSTRAP_ALL_REVERB.sh C172 4
echo "Done with complete reasoning of C172"

sh ./PIPELINE_ALL_REVERB.sh C171
sh ./BOOTSTRAP_ALL_REVERB.sh C171 2
sh ./BOOTSTRAP_ALL_REVERB.sh C171 3
sh ./BOOTSTRAP_ALL_REVERB.sh C171 4
echo "Done with complete reasoning of C171"

sh ./PIPELINE_ALL_REVERB.sh C178
sh ./BOOTSTRAP_ALL_REVERB.sh C178 2
sh ./BOOTSTRAP_ALL_REVERB.sh C178 3
sh ./BOOTSTRAP_ALL_REVERB.sh C178 4
echo "Done with complete reasoning of C178"

sh ./PIPELINE_ALL_REVERB.sh C177
sh ./BOOTSTRAP_ALL_REVERB.sh C177 2
sh ./BOOTSTRAP_ALL_REVERB.sh C177 3
sh ./BOOTSTRAP_ALL_REVERB.sh C177 4
echo "Done with complete reasoning of C177"

sh ./PIPELINE_ALL_REVERB.sh C176
sh ./BOOTSTRAP_ALL_REVERB.sh C176 2
sh ./BOOTSTRAP_ALL_REVERB.sh C176 3
sh ./BOOTSTRAP_ALL_REVERB.sh C176 4
echo "Done with complete reasoning of C176"

sh ./PIPELINE_ALL_REVERB.sh C175
sh ./BOOTSTRAP_ALL_REVERB.sh C175 2
sh ./BOOTSTRAP_ALL_REVERB.sh C175 3
sh ./BOOTSTRAP_ALL_REVERB.sh C175 4
echo "Done with complete reasoning of C175"

sh ./PIPELINE_ALL_REVERB.sh C168
sh ./BOOTSTRAP_ALL_REVERB.sh C168 2
sh ./BOOTSTRAP_ALL_REVERB.sh C168 3
sh ./BOOTSTRAP_ALL_REVERB.sh C168 4
echo "Done with complete reasoning of C168"

sh ./PIPELINE_ALL_REVERB.sh C169
sh ./BOOTSTRAP_ALL_REVERB.sh C169 2
sh ./BOOTSTRAP_ALL_REVERB.sh C169 3
sh ./BOOTSTRAP_ALL_REVERB.sh C169 4
echo "Done with complete reasoning of C169"

sh ./PIPELINE_ALL_REVERB.sh C50
sh ./BOOTSTRAP_ALL_REVERB.sh C50 2
sh ./BOOTSTRAP_ALL_REVERB.sh C50 3
sh ./BOOTSTRAP_ALL_REVERB.sh C50 4
echo "Done with complete reasoning of C50"

sh ./PIPELINE_ALL_REVERB.sh C51
sh ./BOOTSTRAP_ALL_REVERB.sh C51 2
sh ./BOOTSTRAP_ALL_REVERB.sh C51 3
sh ./BOOTSTRAP_ALL_REVERB.sh C51 4
echo "Done with complete reasoning of C51"

sh ./PIPELINE_ALL_REVERB.sh C46
sh ./BOOTSTRAP_ALL_REVERB.sh C46 2
sh ./BOOTSTRAP_ALL_REVERB.sh C46 3
sh ./BOOTSTRAP_ALL_REVERB.sh C46 4
echo "Done with complete reasoning of C46"

sh ./PIPELINE_ALL_REVERB.sh C45
sh ./BOOTSTRAP_ALL_REVERB.sh C45 2
sh ./BOOTSTRAP_ALL_REVERB.sh C45 3
sh ./BOOTSTRAP_ALL_REVERB.sh C45 4
echo "Done with complete reasoning of C45"

sh ./PIPELINE_ALL_REVERB.sh C48
sh ./BOOTSTRAP_ALL_REVERB.sh C48 2
sh ./BOOTSTRAP_ALL_REVERB.sh C48 3
sh ./BOOTSTRAP_ALL_REVERB.sh C48 4
echo "Done with complete reasoning of C48"

sh ./PIPELINE_ALL_REVERB.sh C47
sh ./BOOTSTRAP_ALL_REVERB.sh C47 2
sh ./BOOTSTRAP_ALL_REVERB.sh C47 3
sh ./BOOTSTRAP_ALL_REVERB.sh C47 4
echo "Done with complete reasoning of C47"

sh ./PIPELINE_ALL_REVERB.sh C42
sh ./BOOTSTRAP_ALL_REVERB.sh C42 2
sh ./BOOTSTRAP_ALL_REVERB.sh C42 3
sh ./BOOTSTRAP_ALL_REVERB.sh C42 4
echo "Done with complete reasoning of C42"

sh ./PIPELINE_ALL_REVERB.sh C41
sh ./BOOTSTRAP_ALL_REVERB.sh C41 2
sh ./BOOTSTRAP_ALL_REVERB.sh C41 3
sh ./BOOTSTRAP_ALL_REVERB.sh C41 4
echo "Done with complete reasoning of C41"

sh ./PIPELINE_ALL_REVERB.sh C44
sh ./BOOTSTRAP_ALL_REVERB.sh C44 2
sh ./BOOTSTRAP_ALL_REVERB.sh C44 3
sh ./BOOTSTRAP_ALL_REVERB.sh C44 4
echo "Done with complete reasoning of C44"

sh ./PIPELINE_ALL_REVERB.sh C43
sh ./BOOTSTRAP_ALL_REVERB.sh C43 2
sh ./BOOTSTRAP_ALL_REVERB.sh C43 3
sh ./BOOTSTRAP_ALL_REVERB.sh C43 4
echo "Done with complete reasoning of C43"

sh ./PIPELINE_ALL_REVERB.sh C161
sh ./BOOTSTRAP_ALL_REVERB.sh C161 2
sh ./BOOTSTRAP_ALL_REVERB.sh C161 3
sh ./BOOTSTRAP_ALL_REVERB.sh C161 4
echo "Done with complete reasoning of C161"

sh ./PIPELINE_ALL_REVERB.sh C160
sh ./BOOTSTRAP_ALL_REVERB.sh C160 2
sh ./BOOTSTRAP_ALL_REVERB.sh C160 3
sh ./BOOTSTRAP_ALL_REVERB.sh C160 4
echo "Done with complete reasoning of C160"

sh ./PIPELINE_ALL_REVERB.sh C163
sh ./BOOTSTRAP_ALL_REVERB.sh C163 2
sh ./BOOTSTRAP_ALL_REVERB.sh C163 3
sh ./BOOTSTRAP_ALL_REVERB.sh C163 4
echo "Done with complete reasoning of C163"

sh ./PIPELINE_ALL_REVERB.sh C162
sh ./BOOTSTRAP_ALL_REVERB.sh C162 2
sh ./BOOTSTRAP_ALL_REVERB.sh C162 3
sh ./BOOTSTRAP_ALL_REVERB.sh C162 4
echo "Done with complete reasoning of C162"

sh ./PIPELINE_ALL_REVERB.sh C165
sh ./BOOTSTRAP_ALL_REVERB.sh C165 2
sh ./BOOTSTRAP_ALL_REVERB.sh C165 3
sh ./BOOTSTRAP_ALL_REVERB.sh C165 4
echo "Done with complete reasoning of C165"

sh ./PIPELINE_ALL_REVERB.sh C164
sh ./BOOTSTRAP_ALL_REVERB.sh C164 2
sh ./BOOTSTRAP_ALL_REVERB.sh C164 3
sh ./BOOTSTRAP_ALL_REVERB.sh C164 4
echo "Done with complete reasoning of C164"

sh ./PIPELINE_ALL_REVERB.sh C49
sh ./BOOTSTRAP_ALL_REVERB.sh C49 2
sh ./BOOTSTRAP_ALL_REVERB.sh C49 3
sh ./BOOTSTRAP_ALL_REVERB.sh C49 4
echo "Done with complete reasoning of C49"

sh ./PIPELINE_ALL_REVERB.sh C167
sh ./BOOTSTRAP_ALL_REVERB.sh C167 2
sh ./BOOTSTRAP_ALL_REVERB.sh C167 3
sh ./BOOTSTRAP_ALL_REVERB.sh C167 4
echo "Done with complete reasoning of C167"

sh ./PIPELINE_ALL_REVERB.sh C166
sh ./BOOTSTRAP_ALL_REVERB.sh C166 2
sh ./BOOTSTRAP_ALL_REVERB.sh C166 3
sh ./BOOTSTRAP_ALL_REVERB.sh C166 4
echo "Done with complete reasoning of C166"

sh ./PIPELINE_ALL_REVERB.sh C110
sh ./BOOTSTRAP_ALL_REVERB.sh C110 2
sh ./BOOTSTRAP_ALL_REVERB.sh C110 3
sh ./BOOTSTRAP_ALL_REVERB.sh C110 4
echo "Done with complete reasoning of C110"

sh ./PIPELINE_ALL_REVERB.sh C80
sh ./BOOTSTRAP_ALL_REVERB.sh C80 2
sh ./BOOTSTRAP_ALL_REVERB.sh C80 3
sh ./BOOTSTRAP_ALL_REVERB.sh C80 4
echo "Done with complete reasoning of C80"

sh ./PIPELINE_ALL_REVERB.sh C112
sh ./BOOTSTRAP_ALL_REVERB.sh C112 2
sh ./BOOTSTRAP_ALL_REVERB.sh C112 3
sh ./BOOTSTRAP_ALL_REVERB.sh C112 4
echo "Done with complete reasoning of C112"

sh ./PIPELINE_ALL_REVERB.sh C111
sh ./BOOTSTRAP_ALL_REVERB.sh C111 2
sh ./BOOTSTRAP_ALL_REVERB.sh C111 3
sh ./BOOTSTRAP_ALL_REVERB.sh C111 4
echo "Done with complete reasoning of C111"

sh ./PIPELINE_ALL_REVERB.sh C83
sh ./BOOTSTRAP_ALL_REVERB.sh C83 2
sh ./BOOTSTRAP_ALL_REVERB.sh C83 3
sh ./BOOTSTRAP_ALL_REVERB.sh C83 4
echo "Done with complete reasoning of C83"

sh ./PIPELINE_ALL_REVERB.sh C84
sh ./BOOTSTRAP_ALL_REVERB.sh C84 2
sh ./BOOTSTRAP_ALL_REVERB.sh C84 3
sh ./BOOTSTRAP_ALL_REVERB.sh C84 4
echo "Done with complete reasoning of C84"

sh ./PIPELINE_ALL_REVERB.sh C81
sh ./BOOTSTRAP_ALL_REVERB.sh C81 2
sh ./BOOTSTRAP_ALL_REVERB.sh C81 3
sh ./BOOTSTRAP_ALL_REVERB.sh C81 4
echo "Done with complete reasoning of C81"

sh ./PIPELINE_ALL_REVERB.sh C82
sh ./BOOTSTRAP_ALL_REVERB.sh C82 2
sh ./BOOTSTRAP_ALL_REVERB.sh C82 3
sh ./BOOTSTRAP_ALL_REVERB.sh C82 4
echo "Done with complete reasoning of C82"

sh ./PIPELINE_ALL_REVERB.sh C192
sh ./BOOTSTRAP_ALL_REVERB.sh C192 2
sh ./BOOTSTRAP_ALL_REVERB.sh C192 3
sh ./BOOTSTRAP_ALL_REVERB.sh C192 4
echo "Done with complete reasoning of C192"

sh ./PIPELINE_ALL_REVERB.sh C117
sh ./BOOTSTRAP_ALL_REVERB.sh C117 2
sh ./BOOTSTRAP_ALL_REVERB.sh C117 3
sh ./BOOTSTRAP_ALL_REVERB.sh C117 4
echo "Done with complete reasoning of C117"

sh ./PIPELINE_ALL_REVERB.sh C77
sh ./BOOTSTRAP_ALL_REVERB.sh C77 2
sh ./BOOTSTRAP_ALL_REVERB.sh C77 3
sh ./BOOTSTRAP_ALL_REVERB.sh C77 4
echo "Done with complete reasoning of C77"

sh ./PIPELINE_ALL_REVERB.sh C191
sh ./BOOTSTRAP_ALL_REVERB.sh C191 2
sh ./BOOTSTRAP_ALL_REVERB.sh C191 3
sh ./BOOTSTRAP_ALL_REVERB.sh C191 4
echo "Done with complete reasoning of C191"

sh ./PIPELINE_ALL_REVERB.sh C118
sh ./BOOTSTRAP_ALL_REVERB.sh C118 2
sh ./BOOTSTRAP_ALL_REVERB.sh C118 3
sh ./BOOTSTRAP_ALL_REVERB.sh C118 4
echo "Done with complete reasoning of C118"

sh ./PIPELINE_ALL_REVERB.sh C76
sh ./BOOTSTRAP_ALL_REVERB.sh C76 2
sh ./BOOTSTRAP_ALL_REVERB.sh C76 3
sh ./BOOTSTRAP_ALL_REVERB.sh C76 4
echo "Done with complete reasoning of C76"

sh ./PIPELINE_ALL_REVERB.sh C190
sh ./BOOTSTRAP_ALL_REVERB.sh C190 2
sh ./BOOTSTRAP_ALL_REVERB.sh C190 3
sh ./BOOTSTRAP_ALL_REVERB.sh C190 4
echo "Done with complete reasoning of C190"

sh ./PIPELINE_ALL_REVERB.sh C119
sh ./BOOTSTRAP_ALL_REVERB.sh C119 2
sh ./BOOTSTRAP_ALL_REVERB.sh C119 3
sh ./BOOTSTRAP_ALL_REVERB.sh C119 4
echo "Done with complete reasoning of C119"

sh ./PIPELINE_ALL_REVERB.sh C75
sh ./BOOTSTRAP_ALL_REVERB.sh C75 2
sh ./BOOTSTRAP_ALL_REVERB.sh C75 3
sh ./BOOTSTRAP_ALL_REVERB.sh C75 4
echo "Done with complete reasoning of C75"

sh ./PIPELINE_ALL_REVERB.sh C74
sh ./BOOTSTRAP_ALL_REVERB.sh C74 2
sh ./BOOTSTRAP_ALL_REVERB.sh C74 3
sh ./BOOTSTRAP_ALL_REVERB.sh C74 4
echo "Done with complete reasoning of C74"

sh ./PIPELINE_ALL_REVERB.sh C113
sh ./BOOTSTRAP_ALL_REVERB.sh C113 2
sh ./BOOTSTRAP_ALL_REVERB.sh C113 3
sh ./BOOTSTRAP_ALL_REVERB.sh C113 4
echo "Done with complete reasoning of C113"

sh ./PIPELINE_ALL_REVERB.sh C114
sh ./BOOTSTRAP_ALL_REVERB.sh C114 2
sh ./BOOTSTRAP_ALL_REVERB.sh C114 3
sh ./BOOTSTRAP_ALL_REVERB.sh C114 4
echo "Done with complete reasoning of C114"

sh ./PIPELINE_ALL_REVERB.sh C115
sh ./BOOTSTRAP_ALL_REVERB.sh C115 2
sh ./BOOTSTRAP_ALL_REVERB.sh C115 3
sh ./BOOTSTRAP_ALL_REVERB.sh C115 4
echo "Done with complete reasoning of C115"

sh ./PIPELINE_ALL_REVERB.sh C79
sh ./BOOTSTRAP_ALL_REVERB.sh C79 2
sh ./BOOTSTRAP_ALL_REVERB.sh C79 3
sh ./BOOTSTRAP_ALL_REVERB.sh C79 4
echo "Done with complete reasoning of C79"

sh ./PIPELINE_ALL_REVERB.sh C116
sh ./BOOTSTRAP_ALL_REVERB.sh C116 2
sh ./BOOTSTRAP_ALL_REVERB.sh C116 3
sh ./BOOTSTRAP_ALL_REVERB.sh C116 4
echo "Done with complete reasoning of C116"

sh ./PIPELINE_ALL_REVERB.sh C78
sh ./BOOTSTRAP_ALL_REVERB.sh C78 2
sh ./BOOTSTRAP_ALL_REVERB.sh C78 3
sh ./BOOTSTRAP_ALL_REVERB.sh C78 4
echo "Done with complete reasoning of C78"

sh ./PIPELINE_ALL_REVERB.sh C196
sh ./BOOTSTRAP_ALL_REVERB.sh C196 2
sh ./BOOTSTRAP_ALL_REVERB.sh C196 3
sh ./BOOTSTRAP_ALL_REVERB.sh C196 4
echo "Done with complete reasoning of C196"

sh ./PIPELINE_ALL_REVERB.sh C195
sh ./BOOTSTRAP_ALL_REVERB.sh C195 2
sh ./BOOTSTRAP_ALL_REVERB.sh C195 3
sh ./BOOTSTRAP_ALL_REVERB.sh C195 4
echo "Done with complete reasoning of C195"

sh ./PIPELINE_ALL_REVERB.sh C194
sh ./BOOTSTRAP_ALL_REVERB.sh C194 2
sh ./BOOTSTRAP_ALL_REVERB.sh C194 3
sh ./BOOTSTRAP_ALL_REVERB.sh C194 4
echo "Done with complete reasoning of C194"

sh ./PIPELINE_ALL_REVERB.sh C193
sh ./BOOTSTRAP_ALL_REVERB.sh C193 2
sh ./BOOTSTRAP_ALL_REVERB.sh C193 3
sh ./BOOTSTRAP_ALL_REVERB.sh C193 4
echo "Done with complete reasoning of C193"

sh ./PIPELINE_ALL_REVERB.sh C101
sh ./BOOTSTRAP_ALL_REVERB.sh C101 2
sh ./BOOTSTRAP_ALL_REVERB.sh C101 3
sh ./BOOTSTRAP_ALL_REVERB.sh C101 4
echo "Done with complete reasoning of C101"

sh ./PIPELINE_ALL_REVERB.sh C100
sh ./BOOTSTRAP_ALL_REVERB.sh C100 2
sh ./BOOTSTRAP_ALL_REVERB.sh C100 3
sh ./BOOTSTRAP_ALL_REVERB.sh C100 4
echo "Done with complete reasoning of C100"

sh ./PIPELINE_ALL_REVERB.sh C70
sh ./BOOTSTRAP_ALL_REVERB.sh C70 2
sh ./BOOTSTRAP_ALL_REVERB.sh C70 3
sh ./BOOTSTRAP_ALL_REVERB.sh C70 4
echo "Done with complete reasoning of C70"

sh ./PIPELINE_ALL_REVERB.sh C71
sh ./BOOTSTRAP_ALL_REVERB.sh C71 2
sh ./BOOTSTRAP_ALL_REVERB.sh C71 3
sh ./BOOTSTRAP_ALL_REVERB.sh C71 4
echo "Done with complete reasoning of C71"

sh ./PIPELINE_ALL_REVERB.sh C72
sh ./BOOTSTRAP_ALL_REVERB.sh C72 2
sh ./BOOTSTRAP_ALL_REVERB.sh C72 3
sh ./BOOTSTRAP_ALL_REVERB.sh C72 4
echo "Done with complete reasoning of C72"

sh ./PIPELINE_ALL_REVERB.sh C73
sh ./BOOTSTRAP_ALL_REVERB.sh C73 2
sh ./BOOTSTRAP_ALL_REVERB.sh C73 3
sh ./BOOTSTRAP_ALL_REVERB.sh C73 4
echo "Done with complete reasoning of C73"

sh ./PIPELINE_ALL_REVERB.sh C108
sh ./BOOTSTRAP_ALL_REVERB.sh C108 2
sh ./BOOTSTRAP_ALL_REVERB.sh C108 3
sh ./BOOTSTRAP_ALL_REVERB.sh C108 4
echo "Done with complete reasoning of C108"

sh ./PIPELINE_ALL_REVERB.sh C64
sh ./BOOTSTRAP_ALL_REVERB.sh C64 2
sh ./BOOTSTRAP_ALL_REVERB.sh C64 3
sh ./BOOTSTRAP_ALL_REVERB.sh C64 4
echo "Done with complete reasoning of C64"

sh ./PIPELINE_ALL_REVERB.sh C109
sh ./BOOTSTRAP_ALL_REVERB.sh C109 2
sh ./BOOTSTRAP_ALL_REVERB.sh C109 3
sh ./BOOTSTRAP_ALL_REVERB.sh C109 4
echo "Done with complete reasoning of C109"

sh ./PIPELINE_ALL_REVERB.sh C63
sh ./BOOTSTRAP_ALL_REVERB.sh C63 2
sh ./BOOTSTRAP_ALL_REVERB.sh C63 3
sh ./BOOTSTRAP_ALL_REVERB.sh C63 4
echo "Done with complete reasoning of C63"

sh ./PIPELINE_ALL_REVERB.sh C181
sh ./BOOTSTRAP_ALL_REVERB.sh C181 2
sh ./BOOTSTRAP_ALL_REVERB.sh C181 3
sh ./BOOTSTRAP_ALL_REVERB.sh C181 4
echo "Done with complete reasoning of C181"

sh ./PIPELINE_ALL_REVERB.sh C106
sh ./BOOTSTRAP_ALL_REVERB.sh C106 2
sh ./BOOTSTRAP_ALL_REVERB.sh C106 3
sh ./BOOTSTRAP_ALL_REVERB.sh C106 4
echo "Done with complete reasoning of C106"

sh ./PIPELINE_ALL_REVERB.sh C66
sh ./BOOTSTRAP_ALL_REVERB.sh C66 2
sh ./BOOTSTRAP_ALL_REVERB.sh C66 3
sh ./BOOTSTRAP_ALL_REVERB.sh C66 4
echo "Done with complete reasoning of C66"

sh ./PIPELINE_ALL_REVERB.sh C180
sh ./BOOTSTRAP_ALL_REVERB.sh C180 2
sh ./BOOTSTRAP_ALL_REVERB.sh C180 3
sh ./BOOTSTRAP_ALL_REVERB.sh C180 4
echo "Done with complete reasoning of C180"

sh ./PIPELINE_ALL_REVERB.sh C107
sh ./BOOTSTRAP_ALL_REVERB.sh C107 2
sh ./BOOTSTRAP_ALL_REVERB.sh C107 3
sh ./BOOTSTRAP_ALL_REVERB.sh C107 4
echo "Done with complete reasoning of C107"

sh ./PIPELINE_ALL_REVERB.sh C65
sh ./BOOTSTRAP_ALL_REVERB.sh C65 2
sh ./BOOTSTRAP_ALL_REVERB.sh C65 3
sh ./BOOTSTRAP_ALL_REVERB.sh C65 4
echo "Done with complete reasoning of C65"

sh ./PIPELINE_ALL_REVERB.sh C104
sh ./BOOTSTRAP_ALL_REVERB.sh C104 2
sh ./BOOTSTRAP_ALL_REVERB.sh C104 3
sh ./BOOTSTRAP_ALL_REVERB.sh C104 4
echo "Done with complete reasoning of C104"

sh ./PIPELINE_ALL_REVERB.sh C68
sh ./BOOTSTRAP_ALL_REVERB.sh C68 2
sh ./BOOTSTRAP_ALL_REVERB.sh C68 3
sh ./BOOTSTRAP_ALL_REVERB.sh C68 4
echo "Done with complete reasoning of C68"

sh ./PIPELINE_ALL_REVERB.sh C105
sh ./BOOTSTRAP_ALL_REVERB.sh C105 2
sh ./BOOTSTRAP_ALL_REVERB.sh C105 3
sh ./BOOTSTRAP_ALL_REVERB.sh C105 4
echo "Done with complete reasoning of C105"

sh ./PIPELINE_ALL_REVERB.sh C67
sh ./BOOTSTRAP_ALL_REVERB.sh C67 2
sh ./BOOTSTRAP_ALL_REVERB.sh C67 3
sh ./BOOTSTRAP_ALL_REVERB.sh C67 4
echo "Done with complete reasoning of C67"

sh ./PIPELINE_ALL_REVERB.sh C102
sh ./BOOTSTRAP_ALL_REVERB.sh C102 2
sh ./BOOTSTRAP_ALL_REVERB.sh C102 3
sh ./BOOTSTRAP_ALL_REVERB.sh C102 4
echo "Done with complete reasoning of C102"

sh ./PIPELINE_ALL_REVERB.sh C103
sh ./BOOTSTRAP_ALL_REVERB.sh C103 2
sh ./BOOTSTRAP_ALL_REVERB.sh C103 3
sh ./BOOTSTRAP_ALL_REVERB.sh C103 4
echo "Done with complete reasoning of C103"

sh ./PIPELINE_ALL_REVERB.sh C69
sh ./BOOTSTRAP_ALL_REVERB.sh C69 2
sh ./BOOTSTRAP_ALL_REVERB.sh C69 3
sh ./BOOTSTRAP_ALL_REVERB.sh C69 4
echo "Done with complete reasoning of C69"

sh ./PIPELINE_ALL_REVERB.sh C187
sh ./BOOTSTRAP_ALL_REVERB.sh C187 2
sh ./BOOTSTRAP_ALL_REVERB.sh C187 3
sh ./BOOTSTRAP_ALL_REVERB.sh C187 4
echo "Done with complete reasoning of C187"

sh ./PIPELINE_ALL_REVERB.sh C186
sh ./BOOTSTRAP_ALL_REVERB.sh C186 2
sh ./BOOTSTRAP_ALL_REVERB.sh C186 3
sh ./BOOTSTRAP_ALL_REVERB.sh C186 4
echo "Done with complete reasoning of C186"

sh ./PIPELINE_ALL_REVERB.sh C189
sh ./BOOTSTRAP_ALL_REVERB.sh C189 2
sh ./BOOTSTRAP_ALL_REVERB.sh C189 3
sh ./BOOTSTRAP_ALL_REVERB.sh C189 4
echo "Done with complete reasoning of C189"

sh ./PIPELINE_ALL_REVERB.sh C188
sh ./BOOTSTRAP_ALL_REVERB.sh C188 2
sh ./BOOTSTRAP_ALL_REVERB.sh C188 3
sh ./BOOTSTRAP_ALL_REVERB.sh C188 4
echo "Done with complete reasoning of C188"

sh ./PIPELINE_ALL_REVERB.sh C183
sh ./BOOTSTRAP_ALL_REVERB.sh C183 2
sh ./BOOTSTRAP_ALL_REVERB.sh C183 3
sh ./BOOTSTRAP_ALL_REVERB.sh C183 4
echo "Done with complete reasoning of C183"

sh ./PIPELINE_ALL_REVERB.sh C182
sh ./BOOTSTRAP_ALL_REVERB.sh C182 2
sh ./BOOTSTRAP_ALL_REVERB.sh C182 3
sh ./BOOTSTRAP_ALL_REVERB.sh C182 4
echo "Done with complete reasoning of C182"

sh ./PIPELINE_ALL_REVERB.sh C185
sh ./BOOTSTRAP_ALL_REVERB.sh C185 2
sh ./BOOTSTRAP_ALL_REVERB.sh C185 3
sh ./BOOTSTRAP_ALL_REVERB.sh C185 4
echo "Done with complete reasoning of C185"

sh ./PIPELINE_ALL_REVERB.sh C184
sh ./BOOTSTRAP_ALL_REVERB.sh C184 2
sh ./BOOTSTRAP_ALL_REVERB.sh C184 3
sh ./BOOTSTRAP_ALL_REVERB.sh C184 4
echo "Done with complete reasoning of C184"

sh ./PIPELINE_ALL_REVERB.sh C138
sh ./BOOTSTRAP_ALL_REVERB.sh C138 2
sh ./BOOTSTRAP_ALL_REVERB.sh C138 3
sh ./BOOTSTRAP_ALL_REVERB.sh C138 4
echo "Done with complete reasoning of C138"

sh ./PIPELINE_ALL_REVERB.sh C137
sh ./BOOTSTRAP_ALL_REVERB.sh C137 2
sh ./BOOTSTRAP_ALL_REVERB.sh C137 3
sh ./BOOTSTRAP_ALL_REVERB.sh C137 4
echo "Done with complete reasoning of C137"

sh ./PIPELINE_ALL_REVERB.sh C136
sh ./BOOTSTRAP_ALL_REVERB.sh C136 2
sh ./BOOTSTRAP_ALL_REVERB.sh C136 3
sh ./BOOTSTRAP_ALL_REVERB.sh C136 4
echo "Done with complete reasoning of C136"

sh ./PIPELINE_ALL_REVERB.sh C135
sh ./BOOTSTRAP_ALL_REVERB.sh C135 2
sh ./BOOTSTRAP_ALL_REVERB.sh C135 3
sh ./BOOTSTRAP_ALL_REVERB.sh C135 4
echo "Done with complete reasoning of C135"

sh ./PIPELINE_ALL_REVERB.sh C139
sh ./BOOTSTRAP_ALL_REVERB.sh C139 2
sh ./BOOTSTRAP_ALL_REVERB.sh C139 3
sh ./BOOTSTRAP_ALL_REVERB.sh C139 4
echo "Done with complete reasoning of C139"

sh ./PIPELINE_ALL_REVERB.sh C130
sh ./BOOTSTRAP_ALL_REVERB.sh C130 2
sh ./BOOTSTRAP_ALL_REVERB.sh C130 3
sh ./BOOTSTRAP_ALL_REVERB.sh C130 4
echo "Done with complete reasoning of C130"

sh ./PIPELINE_ALL_REVERB.sh C133
sh ./BOOTSTRAP_ALL_REVERB.sh C133 2
sh ./BOOTSTRAP_ALL_REVERB.sh C133 3
sh ./BOOTSTRAP_ALL_REVERB.sh C133 4
echo "Done with complete reasoning of C133"

sh ./PIPELINE_ALL_REVERB.sh C134
sh ./BOOTSTRAP_ALL_REVERB.sh C134 2
sh ./BOOTSTRAP_ALL_REVERB.sh C134 3
sh ./BOOTSTRAP_ALL_REVERB.sh C134 4
echo "Done with complete reasoning of C134"

sh ./PIPELINE_ALL_REVERB.sh C131
sh ./BOOTSTRAP_ALL_REVERB.sh C131 2
sh ./BOOTSTRAP_ALL_REVERB.sh C131 3
sh ./BOOTSTRAP_ALL_REVERB.sh C131 4
echo "Done with complete reasoning of C131"

sh ./PIPELINE_ALL_REVERB.sh C132
sh ./BOOTSTRAP_ALL_REVERB.sh C132 2
sh ./BOOTSTRAP_ALL_REVERB.sh C132 3
sh ./BOOTSTRAP_ALL_REVERB.sh C132 4
echo "Done with complete reasoning of C132"

sh ./PIPELINE_ALL_REVERB.sh C98
sh ./BOOTSTRAP_ALL_REVERB.sh C98 2
sh ./BOOTSTRAP_ALL_REVERB.sh C98 3
sh ./BOOTSTRAP_ALL_REVERB.sh C98 4
echo "Done with complete reasoning of C98"

sh ./PIPELINE_ALL_REVERB.sh C99
sh ./BOOTSTRAP_ALL_REVERB.sh C99 2
sh ./BOOTSTRAP_ALL_REVERB.sh C99 3
sh ./BOOTSTRAP_ALL_REVERB.sh C99 4
echo "Done with complete reasoning of C99"

sh ./PIPELINE_ALL_REVERB.sh C96
sh ./BOOTSTRAP_ALL_REVERB.sh C96 2
sh ./BOOTSTRAP_ALL_REVERB.sh C96 3
sh ./BOOTSTRAP_ALL_REVERB.sh C96 4
echo "Done with complete reasoning of C96"

sh ./PIPELINE_ALL_REVERB.sh C97
sh ./BOOTSTRAP_ALL_REVERB.sh C97 2
sh ./BOOTSTRAP_ALL_REVERB.sh C97 3
sh ./BOOTSTRAP_ALL_REVERB.sh C97 4
echo "Done with complete reasoning of C97"

sh ./PIPELINE_ALL_REVERB.sh C16
sh ./BOOTSTRAP_ALL_REVERB.sh C16 2
sh ./BOOTSTRAP_ALL_REVERB.sh C16 3
sh ./BOOTSTRAP_ALL_REVERB.sh C16 4
echo "Done with complete reasoning of C16"

sh ./PIPELINE_ALL_REVERB.sh C93
sh ./BOOTSTRAP_ALL_REVERB.sh C93 2
sh ./BOOTSTRAP_ALL_REVERB.sh C93 3
sh ./BOOTSTRAP_ALL_REVERB.sh C93 4
echo "Done with complete reasoning of C93"

sh ./PIPELINE_ALL_REVERB.sh C17
sh ./BOOTSTRAP_ALL_REVERB.sh C17 2
sh ./BOOTSTRAP_ALL_REVERB.sh C17 3
sh ./BOOTSTRAP_ALL_REVERB.sh C17 4
echo "Done with complete reasoning of C17"

sh ./PIPELINE_ALL_REVERB.sh C92
sh ./BOOTSTRAP_ALL_REVERB.sh C92 2
sh ./BOOTSTRAP_ALL_REVERB.sh C92 3
sh ./BOOTSTRAP_ALL_REVERB.sh C92 4
echo "Done with complete reasoning of C92"

sh ./PIPELINE_ALL_REVERB.sh C18
sh ./BOOTSTRAP_ALL_REVERB.sh C18 2
sh ./BOOTSTRAP_ALL_REVERB.sh C18 3
sh ./BOOTSTRAP_ALL_REVERB.sh C18 4
echo "Done with complete reasoning of C18"

sh ./PIPELINE_ALL_REVERB.sh C95
sh ./BOOTSTRAP_ALL_REVERB.sh C95 2
sh ./BOOTSTRAP_ALL_REVERB.sh C95 3
sh ./BOOTSTRAP_ALL_REVERB.sh C95 4
echo "Done with complete reasoning of C95"

sh ./PIPELINE_ALL_REVERB.sh C19
sh ./BOOTSTRAP_ALL_REVERB.sh C19 2
sh ./BOOTSTRAP_ALL_REVERB.sh C19 3
sh ./BOOTSTRAP_ALL_REVERB.sh C19 4
echo "Done with complete reasoning of C19"

sh ./PIPELINE_ALL_REVERB.sh C94
sh ./BOOTSTRAP_ALL_REVERB.sh C94 2
sh ./BOOTSTRAP_ALL_REVERB.sh C94 3
sh ./BOOTSTRAP_ALL_REVERB.sh C94 4
echo "Done with complete reasoning of C94"

sh ./PIPELINE_ALL_REVERB.sh C91
sh ./BOOTSTRAP_ALL_REVERB.sh C91 2
sh ./BOOTSTRAP_ALL_REVERB.sh C91 3
sh ./BOOTSTRAP_ALL_REVERB.sh C91 4
echo "Done with complete reasoning of C91"

sh ./PIPELINE_ALL_REVERB.sh C90
sh ./BOOTSTRAP_ALL_REVERB.sh C90 2
sh ./BOOTSTRAP_ALL_REVERB.sh C90 3
sh ./BOOTSTRAP_ALL_REVERB.sh C90 4
echo "Done with complete reasoning of C90"

sh ./PIPELINE_ALL_REVERB.sh C125
sh ./BOOTSTRAP_ALL_REVERB.sh C125 2
sh ./BOOTSTRAP_ALL_REVERB.sh C125 3
sh ./BOOTSTRAP_ALL_REVERB.sh C125 4
echo "Done with complete reasoning of C125"

sh ./PIPELINE_ALL_REVERB.sh C124
sh ./BOOTSTRAP_ALL_REVERB.sh C124 2
sh ./BOOTSTRAP_ALL_REVERB.sh C124 3
sh ./BOOTSTRAP_ALL_REVERB.sh C124 4
echo "Done with complete reasoning of C124"

sh ./PIPELINE_ALL_REVERB.sh C127
sh ./BOOTSTRAP_ALL_REVERB.sh C127 2
sh ./BOOTSTRAP_ALL_REVERB.sh C127 3
sh ./BOOTSTRAP_ALL_REVERB.sh C127 4
echo "Done with complete reasoning of C127"

sh ./PIPELINE_ALL_REVERB.sh C10
sh ./BOOTSTRAP_ALL_REVERB.sh C10 2
sh ./BOOTSTRAP_ALL_REVERB.sh C10 3
sh ./BOOTSTRAP_ALL_REVERB.sh C10 4
echo "Done with complete reasoning of C10"

sh ./PIPELINE_ALL_REVERB.sh C126
sh ./BOOTSTRAP_ALL_REVERB.sh C126 2
sh ./BOOTSTRAP_ALL_REVERB.sh C126 3
sh ./BOOTSTRAP_ALL_REVERB.sh C126 4
echo "Done with complete reasoning of C126"

sh ./PIPELINE_ALL_REVERB.sh C11
sh ./BOOTSTRAP_ALL_REVERB.sh C11 2
sh ./BOOTSTRAP_ALL_REVERB.sh C11 3
sh ./BOOTSTRAP_ALL_REVERB.sh C11 4
echo "Done with complete reasoning of C11"

sh ./PIPELINE_ALL_REVERB.sh C129
sh ./BOOTSTRAP_ALL_REVERB.sh C129 2
sh ./BOOTSTRAP_ALL_REVERB.sh C129 3
sh ./BOOTSTRAP_ALL_REVERB.sh C129 4
echo "Done with complete reasoning of C129"

sh ./PIPELINE_ALL_REVERB.sh C12
sh ./BOOTSTRAP_ALL_REVERB.sh C12 2
sh ./BOOTSTRAP_ALL_REVERB.sh C12 3
sh ./BOOTSTRAP_ALL_REVERB.sh C12 4
echo "Done with complete reasoning of C12"

sh ./PIPELINE_ALL_REVERB.sh C128
sh ./BOOTSTRAP_ALL_REVERB.sh C128 2
sh ./BOOTSTRAP_ALL_REVERB.sh C128 3
sh ./BOOTSTRAP_ALL_REVERB.sh C128 4
echo "Done with complete reasoning of C128"

sh ./PIPELINE_ALL_REVERB.sh C13
sh ./BOOTSTRAP_ALL_REVERB.sh C13 2
sh ./BOOTSTRAP_ALL_REVERB.sh C13 3
sh ./BOOTSTRAP_ALL_REVERB.sh C13 4
echo "Done with complete reasoning of C13"

sh ./PIPELINE_ALL_REVERB.sh C14
sh ./BOOTSTRAP_ALL_REVERB.sh C14 2
sh ./BOOTSTRAP_ALL_REVERB.sh C14 3
sh ./BOOTSTRAP_ALL_REVERB.sh C14 4
echo "Done with complete reasoning of C14"

sh ./PIPELINE_ALL_REVERB.sh C15
sh ./BOOTSTRAP_ALL_REVERB.sh C15 2
sh ./BOOTSTRAP_ALL_REVERB.sh C15 3
sh ./BOOTSTRAP_ALL_REVERB.sh C15 4
echo "Done with complete reasoning of C15"

sh ./PIPELINE_ALL_REVERB.sh C120
sh ./BOOTSTRAP_ALL_REVERB.sh C120 2
sh ./BOOTSTRAP_ALL_REVERB.sh C120 3
sh ./BOOTSTRAP_ALL_REVERB.sh C120 4
echo "Done with complete reasoning of C120"

sh ./PIPELINE_ALL_REVERB.sh C121
sh ./BOOTSTRAP_ALL_REVERB.sh C121 2
sh ./BOOTSTRAP_ALL_REVERB.sh C121 3
sh ./BOOTSTRAP_ALL_REVERB.sh C121 4
echo "Done with complete reasoning of C121"

sh ./PIPELINE_ALL_REVERB.sh C122
sh ./BOOTSTRAP_ALL_REVERB.sh C122 2
sh ./BOOTSTRAP_ALL_REVERB.sh C122 3
sh ./BOOTSTRAP_ALL_REVERB.sh C122 4
echo "Done with complete reasoning of C122"

sh ./PIPELINE_ALL_REVERB.sh C123
sh ./BOOTSTRAP_ALL_REVERB.sh C123 2
sh ./BOOTSTRAP_ALL_REVERB.sh C123 3
sh ./BOOTSTRAP_ALL_REVERB.sh C123 4
echo "Done with complete reasoning of C123"

sh ./PIPELINE_ALL_REVERB.sh C89
sh ./BOOTSTRAP_ALL_REVERB.sh C89 2
sh ./BOOTSTRAP_ALL_REVERB.sh C89 3
sh ./BOOTSTRAP_ALL_REVERB.sh C89 4
echo "Done with complete reasoning of C89"

sh ./PIPELINE_ALL_REVERB.sh C85
sh ./BOOTSTRAP_ALL_REVERB.sh C85 2
sh ./BOOTSTRAP_ALL_REVERB.sh C85 3
sh ./BOOTSTRAP_ALL_REVERB.sh C85 4
echo "Done with complete reasoning of C85"

sh ./PIPELINE_ALL_REVERB.sh C86
sh ./BOOTSTRAP_ALL_REVERB.sh C86 2
sh ./BOOTSTRAP_ALL_REVERB.sh C86 3
sh ./BOOTSTRAP_ALL_REVERB.sh C86 4
echo "Done with complete reasoning of C86"

sh ./PIPELINE_ALL_REVERB.sh C87
sh ./BOOTSTRAP_ALL_REVERB.sh C87 2
sh ./BOOTSTRAP_ALL_REVERB.sh C87 3
sh ./BOOTSTRAP_ALL_REVERB.sh C87 4
echo "Done with complete reasoning of C87"

sh ./PIPELINE_ALL_REVERB.sh C88
sh ./BOOTSTRAP_ALL_REVERB.sh C88 2
sh ./BOOTSTRAP_ALL_REVERB.sh C88 3
sh ./BOOTSTRAP_ALL_REVERB.sh C88 4
echo "Done with complete reasoning of C88"

sh ./PIPELINE_ALL_REVERB.sh C8
sh ./BOOTSTRAP_ALL_REVERB.sh C8 2
sh ./BOOTSTRAP_ALL_REVERB.sh C8 3
sh ./BOOTSTRAP_ALL_REVERB.sh C8 4
echo "Done with complete reasoning of C8"

sh ./PIPELINE_ALL_REVERB.sh C7
sh ./BOOTSTRAP_ALL_REVERB.sh C7 2
sh ./BOOTSTRAP_ALL_REVERB.sh C7 3
sh ./BOOTSTRAP_ALL_REVERB.sh C7 4
echo "Done with complete reasoning of C7"

sh ./PIPELINE_ALL_REVERB.sh C9
sh ./BOOTSTRAP_ALL_REVERB.sh C9 2
sh ./BOOTSTRAP_ALL_REVERB.sh C9 3
sh ./BOOTSTRAP_ALL_REVERB.sh C9 4
echo "Done with complete reasoning of C9"

sh ./PIPELINE_ALL_REVERB.sh C29
sh ./BOOTSTRAP_ALL_REVERB.sh C29 2
sh ./BOOTSTRAP_ALL_REVERB.sh C29 3
sh ./BOOTSTRAP_ALL_REVERB.sh C29 4
echo "Done with complete reasoning of C29"

sh ./PIPELINE_ALL_REVERB.sh C4
sh ./BOOTSTRAP_ALL_REVERB.sh C4 2
sh ./BOOTSTRAP_ALL_REVERB.sh C4 3
sh ./BOOTSTRAP_ALL_REVERB.sh C4 4
echo "Done with complete reasoning of C4"

sh ./PIPELINE_ALL_REVERB.sh C3
sh ./BOOTSTRAP_ALL_REVERB.sh C3 2
sh ./BOOTSTRAP_ALL_REVERB.sh C3 3
sh ./BOOTSTRAP_ALL_REVERB.sh C3 4
echo "Done with complete reasoning of C3"

sh ./PIPELINE_ALL_REVERB.sh C27
sh ./BOOTSTRAP_ALL_REVERB.sh C27 2
sh ./BOOTSTRAP_ALL_REVERB.sh C27 3
sh ./BOOTSTRAP_ALL_REVERB.sh C27 4
echo "Done with complete reasoning of C27"

sh ./PIPELINE_ALL_REVERB.sh C6
sh ./BOOTSTRAP_ALL_REVERB.sh C6 2
sh ./BOOTSTRAP_ALL_REVERB.sh C6 3
sh ./BOOTSTRAP_ALL_REVERB.sh C6 4
echo "Done with complete reasoning of C6"

sh ./PIPELINE_ALL_REVERB.sh C28
sh ./BOOTSTRAP_ALL_REVERB.sh C28 2
sh ./BOOTSTRAP_ALL_REVERB.sh C28 3
sh ./BOOTSTRAP_ALL_REVERB.sh C28 4
echo "Done with complete reasoning of C28"

sh ./PIPELINE_ALL_REVERB.sh C5
sh ./BOOTSTRAP_ALL_REVERB.sh C5 2
sh ./BOOTSTRAP_ALL_REVERB.sh C5 3
sh ./BOOTSTRAP_ALL_REVERB.sh C5 4
echo "Done with complete reasoning of C5"

sh ./PIPELINE_ALL_REVERB.sh C25
sh ./BOOTSTRAP_ALL_REVERB.sh C25 2
sh ./BOOTSTRAP_ALL_REVERB.sh C25 3
sh ./BOOTSTRAP_ALL_REVERB.sh C25 4
echo "Done with complete reasoning of C25"

sh ./PIPELINE_ALL_REVERB.sh C26
sh ./BOOTSTRAP_ALL_REVERB.sh C26 2
sh ./BOOTSTRAP_ALL_REVERB.sh C26 3
sh ./BOOTSTRAP_ALL_REVERB.sh C26 4
echo "Done with complete reasoning of C26"

sh ./PIPELINE_ALL_REVERB.sh C23
sh ./BOOTSTRAP_ALL_REVERB.sh C23 2
sh ./BOOTSTRAP_ALL_REVERB.sh C23 3
sh ./BOOTSTRAP_ALL_REVERB.sh C23 4
echo "Done with complete reasoning of C23"

sh ./PIPELINE_ALL_REVERB.sh C24
sh ./BOOTSTRAP_ALL_REVERB.sh C24 2
sh ./BOOTSTRAP_ALL_REVERB.sh C24 3
sh ./BOOTSTRAP_ALL_REVERB.sh C24 4
echo "Done with complete reasoning of C24"

sh ./PIPELINE_ALL_REVERB.sh C21
sh ./BOOTSTRAP_ALL_REVERB.sh C21 2
sh ./BOOTSTRAP_ALL_REVERB.sh C21 3
sh ./BOOTSTRAP_ALL_REVERB.sh C21 4
echo "Done with complete reasoning of C21"

sh ./PIPELINE_ALL_REVERB.sh C159
sh ./BOOTSTRAP_ALL_REVERB.sh C159 2
sh ./BOOTSTRAP_ALL_REVERB.sh C159 3
sh ./BOOTSTRAP_ALL_REVERB.sh C159 4
echo "Done with complete reasoning of C159"

sh ./PIPELINE_ALL_REVERB.sh C22
sh ./BOOTSTRAP_ALL_REVERB.sh C22 2
sh ./BOOTSTRAP_ALL_REVERB.sh C22 3
sh ./BOOTSTRAP_ALL_REVERB.sh C22 4
echo "Done with complete reasoning of C22"

sh ./PIPELINE_ALL_REVERB.sh C158
sh ./BOOTSTRAP_ALL_REVERB.sh C158 2
sh ./BOOTSTRAP_ALL_REVERB.sh C158 3
sh ./BOOTSTRAP_ALL_REVERB.sh C158 4
echo "Done with complete reasoning of C158"

sh ./PIPELINE_ALL_REVERB.sh C157
sh ./BOOTSTRAP_ALL_REVERB.sh C157 2
sh ./BOOTSTRAP_ALL_REVERB.sh C157 3
sh ./BOOTSTRAP_ALL_REVERB.sh C157 4
echo "Done with complete reasoning of C157"

sh ./PIPELINE_ALL_REVERB.sh C20
sh ./BOOTSTRAP_ALL_REVERB.sh C20 2
sh ./BOOTSTRAP_ALL_REVERB.sh C20 3
sh ./BOOTSTRAP_ALL_REVERB.sh C20 4
echo "Done with complete reasoning of C20"

sh ./PIPELINE_ALL_REVERB.sh C155
sh ./BOOTSTRAP_ALL_REVERB.sh C155 2
sh ./BOOTSTRAP_ALL_REVERB.sh C155 3
sh ./BOOTSTRAP_ALL_REVERB.sh C155 4
echo "Done with complete reasoning of C155"

sh ./PIPELINE_ALL_REVERB.sh C156
sh ./BOOTSTRAP_ALL_REVERB.sh C156 2
sh ./BOOTSTRAP_ALL_REVERB.sh C156 3
sh ./BOOTSTRAP_ALL_REVERB.sh C156 4
echo "Done with complete reasoning of C156"

sh ./PIPELINE_ALL_REVERB.sh C153
sh ./BOOTSTRAP_ALL_REVERB.sh C153 2
sh ./BOOTSTRAP_ALL_REVERB.sh C153 3
sh ./BOOTSTRAP_ALL_REVERB.sh C153 4
echo "Done with complete reasoning of C153"

sh ./PIPELINE_ALL_REVERB.sh C154
sh ./BOOTSTRAP_ALL_REVERB.sh C154 2
sh ./BOOTSTRAP_ALL_REVERB.sh C154 3
sh ./BOOTSTRAP_ALL_REVERB.sh C154 4
echo "Done with complete reasoning of C154"

sh ./PIPELINE_ALL_REVERB.sh C151
sh ./BOOTSTRAP_ALL_REVERB.sh C151 2
sh ./BOOTSTRAP_ALL_REVERB.sh C151 3
sh ./BOOTSTRAP_ALL_REVERB.sh C151 4
echo "Done with complete reasoning of C151"

sh ./PIPELINE_ALL_REVERB.sh C152
sh ./BOOTSTRAP_ALL_REVERB.sh C152 2
sh ./BOOTSTRAP_ALL_REVERB.sh C152 3
sh ./BOOTSTRAP_ALL_REVERB.sh C152 4
echo "Done with complete reasoning of C152"

sh ./PIPELINE_ALL_REVERB.sh C150
sh ./BOOTSTRAP_ALL_REVERB.sh C150 2
sh ./BOOTSTRAP_ALL_REVERB.sh C150 3
sh ./BOOTSTRAP_ALL_REVERB.sh C150 4
echo "Done with complete reasoning of C150"

sh ./PIPELINE_ALL_REVERB.sh C38
sh ./BOOTSTRAP_ALL_REVERB.sh C38 2
sh ./BOOTSTRAP_ALL_REVERB.sh C38 3
sh ./BOOTSTRAP_ALL_REVERB.sh C38 4
echo "Done with complete reasoning of C38"

sh ./PIPELINE_ALL_REVERB.sh C39
sh ./BOOTSTRAP_ALL_REVERB.sh C39 2
sh ./BOOTSTRAP_ALL_REVERB.sh C39 3
sh ./BOOTSTRAP_ALL_REVERB.sh C39 4
echo "Done with complete reasoning of C39"

sh ./PIPELINE_ALL_REVERB.sh C34
sh ./BOOTSTRAP_ALL_REVERB.sh C34 2
sh ./BOOTSTRAP_ALL_REVERB.sh C34 3
sh ./BOOTSTRAP_ALL_REVERB.sh C34 4
echo "Done with complete reasoning of C34"

sh ./PIPELINE_ALL_REVERB.sh C35
sh ./BOOTSTRAP_ALL_REVERB.sh C35 2
sh ./BOOTSTRAP_ALL_REVERB.sh C35 3
sh ./BOOTSTRAP_ALL_REVERB.sh C35 4
echo "Done with complete reasoning of C35"

sh ./PIPELINE_ALL_REVERB.sh C36
sh ./BOOTSTRAP_ALL_REVERB.sh C36 2
sh ./BOOTSTRAP_ALL_REVERB.sh C36 3
sh ./BOOTSTRAP_ALL_REVERB.sh C36 4
echo "Done with complete reasoning of C36"

sh ./PIPELINE_ALL_REVERB.sh C37
sh ./BOOTSTRAP_ALL_REVERB.sh C37 2
sh ./BOOTSTRAP_ALL_REVERB.sh C37 3
sh ./BOOTSTRAP_ALL_REVERB.sh C37 4
echo "Done with complete reasoning of C37"

sh ./PIPELINE_ALL_REVERB.sh C147
sh ./BOOTSTRAP_ALL_REVERB.sh C147 2
sh ./BOOTSTRAP_ALL_REVERB.sh C147 3
sh ./BOOTSTRAP_ALL_REVERB.sh C147 4
echo "Done with complete reasoning of C147"

sh ./PIPELINE_ALL_REVERB.sh C30
sh ./BOOTSTRAP_ALL_REVERB.sh C30 2
sh ./BOOTSTRAP_ALL_REVERB.sh C30 3
sh ./BOOTSTRAP_ALL_REVERB.sh C30 4
echo "Done with complete reasoning of C30"

sh ./PIPELINE_ALL_REVERB.sh C146
sh ./BOOTSTRAP_ALL_REVERB.sh C146 2
sh ./BOOTSTRAP_ALL_REVERB.sh C146 3
sh ./BOOTSTRAP_ALL_REVERB.sh C146 4
echo "Done with complete reasoning of C146"

sh ./PIPELINE_ALL_REVERB.sh C31
sh ./BOOTSTRAP_ALL_REVERB.sh C31 2
sh ./BOOTSTRAP_ALL_REVERB.sh C31 3
sh ./BOOTSTRAP_ALL_REVERB.sh C31 4
echo "Done with complete reasoning of C31"

sh ./PIPELINE_ALL_REVERB.sh C149
sh ./BOOTSTRAP_ALL_REVERB.sh C149 2
sh ./BOOTSTRAP_ALL_REVERB.sh C149 3
sh ./BOOTSTRAP_ALL_REVERB.sh C149 4
echo "Done with complete reasoning of C149"

sh ./PIPELINE_ALL_REVERB.sh C32
sh ./BOOTSTRAP_ALL_REVERB.sh C32 2
sh ./BOOTSTRAP_ALL_REVERB.sh C32 3
sh ./BOOTSTRAP_ALL_REVERB.sh C32 4
echo "Done with complete reasoning of C32"

sh ./PIPELINE_ALL_REVERB.sh C148
sh ./BOOTSTRAP_ALL_REVERB.sh C148 2
sh ./BOOTSTRAP_ALL_REVERB.sh C148 3
sh ./BOOTSTRAP_ALL_REVERB.sh C148 4
echo "Done with complete reasoning of C148"

sh ./PIPELINE_ALL_REVERB.sh C33
sh ./BOOTSTRAP_ALL_REVERB.sh C33 2
sh ./BOOTSTRAP_ALL_REVERB.sh C33 3
sh ./BOOTSTRAP_ALL_REVERB.sh C33 4
echo "Done with complete reasoning of C33"

sh ./PIPELINE_ALL_REVERB.sh C142
sh ./BOOTSTRAP_ALL_REVERB.sh C142 2
sh ./BOOTSTRAP_ALL_REVERB.sh C142 3
sh ./BOOTSTRAP_ALL_REVERB.sh C142 4
echo "Done with complete reasoning of C142"

sh ./PIPELINE_ALL_REVERB.sh C143
sh ./BOOTSTRAP_ALL_REVERB.sh C143 2
sh ./BOOTSTRAP_ALL_REVERB.sh C143 3
sh ./BOOTSTRAP_ALL_REVERB.sh C143 4
echo "Done with complete reasoning of C143"

sh ./PIPELINE_ALL_REVERB.sh C144
sh ./BOOTSTRAP_ALL_REVERB.sh C144 2
sh ./BOOTSTRAP_ALL_REVERB.sh C144 3
sh ./BOOTSTRAP_ALL_REVERB.sh C144 4
echo "Done with complete reasoning of C144"

sh ./PIPELINE_ALL_REVERB.sh C40
sh ./BOOTSTRAP_ALL_REVERB.sh C40 2
sh ./BOOTSTRAP_ALL_REVERB.sh C40 3
sh ./BOOTSTRAP_ALL_REVERB.sh C40 4
echo "Done with complete reasoning of C40"

sh ./PIPELINE_ALL_REVERB.sh C145
sh ./BOOTSTRAP_ALL_REVERB.sh C145 2
sh ./BOOTSTRAP_ALL_REVERB.sh C145 3
sh ./BOOTSTRAP_ALL_REVERB.sh C145 4
echo "Done with complete reasoning of C145"

sh ./PIPELINE_ALL_REVERB.sh C140
sh ./BOOTSTRAP_ALL_REVERB.sh C140 2
sh ./BOOTSTRAP_ALL_REVERB.sh C140 3
sh ./BOOTSTRAP_ALL_REVERB.sh C140 4
echo "Done with complete reasoning of C140"

sh ./PIPELINE_ALL_REVERB.sh C141
sh ./BOOTSTRAP_ALL_REVERB.sh C141 2
sh ./BOOTSTRAP_ALL_REVERB.sh C141 3
sh ./BOOTSTRAP_ALL_REVERB.sh C141 4
echo "Done with complete reasoning of C141"

sh ./PIPELINE_ALL_REVERB.sh C1
sh ./BOOTSTRAP_ALL_REVERB.sh C1 2
echo "Done with complete reasoning of C1"

sh ./PIPELINE_ALL_REVERB.sh C2
sh ./BOOTSTRAP_ALL_REVERB.sh C2 2
echo "Done with complete reasoning of C2"
